### ISSUE TITLE
tdrop on dwm?

### ISSUE THREAD

**Issue by se7en-x230** [noctuid/tdrop#108]
I can't get tdrop as a dropdown work on DWM. Any help is welcome.

**Comment by RaafatTurki** [comment]
The terminal emulator you use is a big factor, Try a different terminal maybe? in my experience st doesn't work (even on bspwm)

**Comment by kusky3** [comment]
> I can't get tdrop as a dropdown work on DWM. Any help is welcome.

modify the dwm config.h  and set:
static const Rule rules[] = {
        { "st",     NULL,       NULL,       0,            1,           -1 },
};
if you use st on tiling then set alacritty on floating.

**Comment by Walkability** [comment]
> I can't get tdrop as a dropdown work on DWM. Any help is welcome.
```
	{ Mod1Mask,              XK_semicolon,      spawn,       SHCMD("~/bin/tdrop-alacritty") },
```

**Comment by YorikGK** [comment]
{ MODKEY,   XK_grave,   spawn,   CMD("tdrop -a st") },

You have forgot spaces in the tdrop command.

**Comment by sunnyrahul25** [comment]
It work but I am having problem setting multiple drop down for the same terminal. 
tdrop -ma -w 80% -h 80% -x 25% -y 25% --wm dwm -f '--class ws-term'  alacritty
tdrop -ma -w 80% -h 80% -x 25% -y 25% --wm dwm -f '--class ws-mpv'  alacritty
opens the same instance 

I also see the following log while running above command.
Your windowmanager claims not to support _NET_CURRENT_DESKTOP, so the query for the current desktop was aborted.
Your windowmanager claims not to support _NET_WM_DESKTOP, so the attempt to change a window's desktop location was aborted.
xdo_set_desktop_for_window on window 48234498, desktop 0 failed
