### ISSUE TITLE
Allow '--option value' Syntax for Long Options

### ISSUE THREAD

**Issue by noctuid** [noctuid/tdrop#12]
Using the '-)' hack with getopts is limited in that it requires the `--option=value` syntax. Maybe there is a way to access the next argument and then shift over, but that would be even uglier and would still require manually differentiating arguments that take values from those that don't (instead of using getopts' ":"). It may be better to do something like what is done in the article mentioned in #8.

**Comment by noctuid** [comment]
@schoettl 
"$*" doesn't keep any quotes or escape the arguments, so I'm going to have to iterate over "$@" like you suggest. I could maybe create a string with quotes by iterating over "$@" and requoting arguments with spaces, but it's probably a better idea to do it like in the article. I also need to make sure I'm not changing anything in the `-f` argument.

You can actually do this:
```
sed 's/text/text/
s/text/text/
...'
```
I think the heredoc looks nicer than either, so I'll probably use that. Thanks.

You mean $IFS? You don't actually need to take the other characters into account, since the word splitting has already been done and "$*" doesn't know what the original separators are (it will use a single space).

Yes, even though there aren't any options that it would make sense to use twice, tdrop should still work correctly in those cases. Thanks for pointing this out.

**Comment by schoettl** [comment]
I am not sure if it's `$IFS`. Consider these cases:

```
$ echo<Tab>"foo"
foo
$ echo "foo"
foo
$ echo\
> "foo"
-bash: echofoo: command not found
$ echo^M"foo"
-bash: $'echo\rfoo': command not found
```

What I'm trying to say is that Space is not the only character that can separate a long-option from it's argument! Tab (Ctrl-V, Tab in the terminal) is also a word separation char. CR (Ctrl-V, Return in the terminal) is not.

Anyway, to cover all cases `s/...(=| )/.../` is not enough.

> I also need to make sure I'm not changing anything in the -f argument.

Good point!

Bash can be really complicated with word splitting ... :/

Oh, and still, don't forget word boundary in the regex (`s/\b--.../.../`).

**Comment by noctuid** [comment]
Yeah, IFS determines what characters bash does the word splitting on. What I mean is that bash has already done the word splitting and put each argument into "$@", so you don't have to worry about whether the user used tabs or newlines to separate their arguments with "$*" because it will separate each item in the "$@" array with the first character of IFS. `IFS=$'\n'; echo "$*"` will separate each argument by newlines, so I'm going to try using sed with that and `s/^--option(=|\n)/-o\n/`.

**Comment by schoettl** [comment]
Oh OK, got it. Sounds good to let Bash do the word splitting. I hope though that no user uses arguments with line breaks.

I think `$IFS` must be reset after that.

**Comment by noctuid** [comment]
I've fixed the big problems, but it won't work in some cases. For the options like `-n` and `-f` that could potentially have a tdrop flag in a quoted argument, I'm putting a space in front of the values to prevent them from being matched in the search string later on.

Using newlines doesn't really work well with sed. Also, using a character from the default IFS is a problem if someone uses it in a quoted argument. For example, a technically correct argument to `-f` could still be altered even with the space in front (\t stands for a tab):
```
-f "\t--height"
```
It makes it a little uglier, but I'm using "\r". I couldn't figure out how to get sed to work with a heredoc when something is being piped into it either (as opposed to reading from a file).

Unfortunately, this padding method isn't foolproof. For example, if I pad `--program-flags`'s argument first, I can prevent `--width 8` from being changed to `-w 8`, but the `--program-flags` in `--session` will still be changed to `-f`:
```
tdrop --session "--program-flags" --program-flags "--width 8"
```

This wouldn't actually cause a problem with the `-s` and `-n` options, and for the other options it's extremely unlikely (impossible as far as I know) that they could contain one of these tdrop flags and be valid, but the behavior is still not correct. I think I'd rather force using `=` than have that.

I think the only way around this is to iterate over the arguments and skip the next argument for options that take values. I guess I'll try the iterative approach and decide if it's worth the complexity.

**Comment by schoettl** [comment]
I just got another idea: How about pre-processing the arguments in a loop over `"$@"` and splitting up every `--long-option="..."` into two array elements `--long-option` and `"..."`. After this pre-processing we could literally implement the suggested solution from the blog article.

The advantage was, that in the blog article every single argument is compared like this: `case $i in --long-option) ... ;;`. So no trouble with word-boundaries and complicated sed regexes.

What do you think about this? Do you like to give it a try, or also I could give it a try this evening.

**Comment by schoettl** [comment]
Regarding the Here Document... I didn't think of having already input. But there is still a solution:

```
echo "foo" | sed -rf <(cat <<EOF
s/^f.*/bar/
EOF
)
```
or the other way round:
```
sed -rf -    <(echo "foo")    <<EOF
s/^f.*/bar/
EOF
```

**Comment by noctuid** [comment]
Thanks! I should have thought to try `<(echo ..)`.

The reason I wouldn't want to do any pre-processing (at least not with sed) is because I wouldn't want to touch `--long-option=` if it was the argument to a tdrop option (which could potentially split up an argument to `-f`). Iterating over the arguments prevents needing to have the same complicated regex, but without pre-processing, it will need a different entry for `--width` vs. `--width=`. I'll go ahead and try it out.

**Comment by schoettl** [comment]
Oh, yeah I forgot about the option argument problem again ...

Good luck. I'm looking forward!

**Comment by noctuid** [comment]
It's funny how problem after problem keeps popping up... If only getopts just had support for this in the first place.

Doing something like this works:
```
pass=false
args=()
for arg do
	if $pass; then
		pass=false
		args+=("$arg")
	else
		case "$arg" in
			--height|-h) args+=('-h'); pass=true;;
			--height=*) args+=('-h'); args+=("${arg#*=}");;
			--help|-H) args+=('-H');;
			*) print_help illegal_opt;;
		esac
	fi
done
```

However, this breaks having multiple short options together like `tdrop -am ...`.

I think I've found the best way to allow for spaces:
```
if [[ $OPTARG == *=* ]]; then
	OPTION=${OPTARG%%=*}
	OPTARG=${OPTARG#*=}
else
	OPTION=$OPTARG
	# get the next argument to be parsed
	OPTARG=${*:$OPTIND:1}
	# skip parsing it
	((OPTIND++))
fi
```

I kind of feel stupid for not trying this sooner. Altering the arguments with sed seemed more concise, but I think maybe it's better to leave as much of the argument parsing as possible to getopts. I need to test it more, but I can't think of any problems this would cause.

**Comment by schoettl** [comment]
Your last code snippet is for your original solution, with the case `-) case $OPTARG in ...`, isn't it?

I don't quite understand the `${*:$OPTIND:1}` syntax. Is is a "sublist" of length one? And isn't it better to use `$@` instead of `$*` (my rule of thumb: never use `$*` ^^)?

I wasn't aware of, that one can change `$OPTIND` and `getopts` works accordingly! This sounds like a pretty nice solution! I hope it works!!

**Comment by noctuid** [comment]
Yes, the full code is in the last commit mentioned.

The only reason I used `$*` is because shellcheck gives a warning. It complains with "assigning an array to a string". I guess shellcheck can't tell when you're only taking a single element from an array. The result is the same either way for this case, but I'll use "$@" since it's more recognizable, more correct really, and `${*...}` can have different behavior when you quote it depending on the shell. If you want to treat the arguments as a string (like I was doing with sed) `$*` makes sense, but this probably almost never useful.

Yeah I just assumed something like this wouldn't work earlier. I'll probably commit this into master tomorrow.

**Comment by schoettl** [comment]
Cool! This shellcheck warning can maybe be suppressed when we write something like:
```
OPTARG=${@[$OPTIND]}
```
I think this syntax is specifically for Bash array variables like `$@`.

Otherwise we can suppress the shellcheck warning with a special comment.

**Comment by noctuid** [comment]
It still gives the same warning. I didn't know warning could be suppressed with comments; thanks for that information.

**Comment by noctuid** [comment]
Alright, everything is working as expected.
