### ISSUE TITLE
Question: future and Wayland

### ISSUE THREAD

**Issue by Jiehong** [noctuid/tdrop#13]
Hello,

tdrop is a great application, but as it depends on xprop, xwininfo and xdotool, I was wondering what will happen on Wayland as those are X11 related only?

Would there be a more generic way to do the same thing?

**Comment by Jiehong** [comment]
Thanks for the answer :)

**Comment by mxmilkb** [comment]
A broad FYI; https://github.com/ReimuNotMoe/ydotool is a thing now. If it doesn't have the features requires yet, a request would be worth making upstream, given `wayland`/etc. is an evolving thing. See also wlroots. `xprop` info could probably be parsed from swaymsg, but I'm oblivious as to the mechanisms used by GNOME and KDE DEs or of any apps that abstract the lot. 

Basically put; I don't think there's a cross-Wayland method yet, but targeting the top 3 Wayland implementations now might probably be a somewhat broad but fair starter goal?

**Comment by noctuid** [comment]
I don't think that ydotool has any of the required functionality. It looks like it only is related to input functionality; tdrop uses only the window management related functionality of xdotool.

Tdrop is so tied to X as this point that I'm not sure if it would even be worth generalizing it to work with Wayland. It might make sense for anyone interested to write their own script that handles different implementations. Or if wlroots was widely used, the required functionality could just be part of it (if it would make sense/be possible).

I may never use Wayland and don't have much time to work on tdrop at all at the moment. I also don't want to add even more implementation-specific code to tdrop (I'd like to remove as much of it as possible). If there was a simple, universal way of doing the following in Wayland, creating a tdrop equivalent would be fairly easy:

- getting a unique id of the first visible window created when running a program
- hiding/showing (or "mapping" and "unmapping") and activating windows using an id
- setting the width, height, and positioning of windows using an id (preferably with a way to do based on percentage of current monitor or entire screen setup)
- floating a window using an id

These would be the main things required at least. Xdotool makes hiding/showing and resizing fairly easy. It doesn't allow specifying percentage width for a single monitor, but xrandr can be used for that. There's no universal way to handle floating with X; tdrop has to do it differently for each WM, which is unfortunate.

I'm not necessarily against support for Wayland, but it it seems like at the moment it would be comparably complex (and X is already bad) and probably impossible or at least incomplete on some implementations. I doubt that will change anytime soon. If everything is possible on the main implementations, I might be okay with using a script that wrapped different implementations into a single interface. I can answer questions if anyone else takes an interest on working on anything related, but I won't be working on this myself (at least for now).

**Comment by noctuid** [comment]
Closing for now since there is nothing for me to do. If wayland gets utilities like xdotool in the future, I can reopen.
