### ISSUE TITLE
x/y percentage not working (goal: centering dropdown window)

### ISSUE THREAD

**Issue by quite** [noctuid/tdrop#19]
Manual says:
       -x,  --x-offset
              Specify the x position for a created window as a number or  per‐
              centage. (default: 0)

But setting this to a percentage don't seem to work at all. It's parsed as an absolute number anyway. My goal would be to centre the dropdown window on the monitor. An option for that would be swell : )

**Comment by quite** [comment]
So, the issue is that xdotool doesn't take % for x y.

**Comment by noctuid** [comment]
Okay, it should be working now. For example to center the dropdown on the y axis:

```
tdrop -ma -h 50% -y 25% xterm
```

Let me know if you encounter any problems.
