### ISSUE TITLE
unable to turn a chromium-browser window into a dropdown

### ISSUE THREAD

**Issue by berkan** [noctuid/tdrop#20]
hiya

i'm running bspwm 0.9.1-82.  `tdrop -a chromium-browser`  successfully creates a new floating chromium-browser window, but it cannot resize the window or move it to a center location afterwards.

that's because in function `create_win_return_wid`, it enters a never-ending loop using xdotool to look for the window id  given the PID 

    ++++ xdotool search --pid 10445
    +++ wids=
    +++ [[ -n '' ]]
    +++ false
    +++ sleep 0.01
    +++ :

i don't think this approach (for finding the window id) works for chromium-browser, and i don't know what else can. 

have you been able to create a dropdown with a chromium instance?

cheers,
b.

**Comment by noctuid** [comment]
No, it didn't work previously because of how chromium handles processes. Please try it now.

**Comment by berkan** [comment]
it works now, thank you very much.

note that xfce4-terminal had exactly the same issue for me, so i simply copied your solution and that works too.
```
        elif [[ $program =~ ^xfce4-terminal ]]; then
                pid=$(pgrep -a xfce4-terminal | awk '!/--type/ {print $1}')
                eval "$program_command"
```

**Comment by noctuid** [comment]
Thanks for pointing that out; xfce4-terminal should now work without changes. I made a couple changes, so could you tell me if it still works with chromium or give me the output of `pgrep -l chromium`? It seems there are different names for chromium/chrome based on the distro (for me chromium is just `chromium`), but it seems the process names may just be `chrome` or `chromium` regardless.

**Comment by berkan** [comment]
hi again - 

xfce4-terminal does indeed work, thank you.

the updates for chromium did work initially, and then all of a sudden it reverted back to the infinite loop case. something must have happened to cause it, but i'm really at a loss to explain.

when i change the code back to how it was after your initial fix (ie when i don't demand `pgrep -x`), it again works:

```
        elif [[ $program =~ ^chromium ]]; then   #BE# && pgrep -x chromium; then
                # this may work fine
                # pid=$(pgrep -o chromium)
                #BE#pid=$(pgrep -xa chromium | awk '!/--type/ {print $1}')
                pid=$(pgrep -a chromium | awk '!/--type/ {print $1}') 
                eval "$program_command"
```

also - the output of `prep -l` is

```
593 chromium-browse
797 chromium-browse
891 chromium-browse
:
:
```

i'm running xubuntu 16.04.

**Comment by noctuid** [comment]
Sorry about that. I'd rather use `pgrep -x` to prevent problems if another program with "chromium" in the name happens to be running. I've added an explicit check for `chromium-browser` with a process name of `chromium-browse`, so it should be working now. Please let me know if you have any problems.
