### ISSUE TITLE
Multiple scratchpads doesn't work

### ISSUE THREAD

**Issue by wedens** [noctuid/tdrop#22]
I'm trying to use two scratchpads`tdrop -a -w 1880 -y 14 -x 20 -f '--name=term-scratchpad' termite` and `tdrop -a -w 1880 -y 14 -x 20 -f '--name=ranger-scratchpad -e ranger' termite`.
Both commands will show only the first created scratchpad.

**Comment by noctuid** [comment]
You need to use tdrop's `-n`/`--number` for additional scratchpads of the same program. The argument does not have to be a number. For example:

```
tdrop -n ranger <other flags...> termite
```
