### ISSUE TITLE
Inconsistent support on BSPWM

### ISSUE THREAD

**Issue by Gingernaut** [noctuid/tdrop#23]
I'm using tdrop with bspwm; about 50% of the time, the binding opens a terminal in the default floating state (middle of the screen and a small window) rather than the drop-down behavior I'd like.

Here's the binding I'm using:
alt + v
    tdrop -a -w 100% -h 50% urxvt

**Comment by noctuid** [comment]
Yes, I noticed that this started happening with newer versions of bspwm, but it only happened to me maybe 1% of the time, so I didn't bother changing it. The fix is harmless for older versions, so I went ahead and added it. Let me know if the problem is still happening for you after updating.

**Comment by Gingernaut** [comment]
I've updated the the latest development version from the AUR and unfortunately I'm still facing the same issue. (Actually it opens in the default tiling mode 100% of the time). Is there any information I can provide that would be helpful?

**Comment by noctuid** [comment]
There's been a lot of breaking changes to bspwm (specifically the rule syntax in this case), and I currently have code to support older versions, so I'm depending on the version number of bspwm (at least until I drop support for older versions).  What's the output of `bspwm -v`?

**Comment by noctuid** [comment]
I went ahead and dropped support for older versions of bspwm. Assuming you are on 0.9.1 or higher, this may fix the problem. If you are on the development version of bspwm, and this doesn't fix the problem, there may have been more breaking changes that I will need to look into.

**Comment by Gingernaut** [comment]
bspwm -v outputs 0.9.1. After some further testing, tdrop works with termite and lilyterm but not with urxvt.
Here are my urxvt settings: https://github.com/Gingernaut/dotfiles/blob/master/x_files/.Xresources

**Comment by noctuid** [comment]
I tested with your config and was unable to replicate the error. Just to confirm, the problem is still that urxvt isn't being floated, right?

After running the following, is the next instance of urxvt floated?
```
bspc rule -a \*:"urxvt" -o state=floating
```

Are you using rxvt-unicode from the official repos or a version from the aur? Could you give me the output of the following run from urxvt?
```
xprop -id "$(xdotool getactivewindow)" WM_CLASS
```

**Comment by Gingernaut** [comment]
The output of the second command is: WM_CLASS(STRING) = "urxvt", "URxvt". I am using urxvt from aur packages. running the bspc rule did float the urxvt window, but not in the drop-down style. It was floating previously as well.

**Comment by noctuid** [comment]
Just to confirm, what exactly happens when you press the hotkey bound to the urxvt dropdown? Does it work but urxvt is tiled instead of floating? Does urxt not appear at all?

> running the bspc rule did float the urxvt window, but not in the drop-down style. It was floating previously as well.

What window was floating previously? Did you open a new urxvt after running the rule?
