### ISSUE TITLE
gnome-terminal not getting resized

### ISSUE THREAD

**Issue by pschmitt** [noctuid/tdrop#25]
Hi,

I discovered that launching gnome-terminal with tdrop does not work properly. The window does not get resized.

The loop of line 515 is infinite since `wids=$(xdotool search --pid "$pid")` does not find anything.

EDIT: Fixed line number

**Comment by noctuid** [comment]
Thanks for reporting. It should be fixed now. Let me know if you have any more problems.

**Comment by pschmitt** [comment]
Nice. Thanks!
