### ISSUE TITLE
Add support for alacritty

### ISSUE THREAD

**Issue by ibrokemypie** [noctuid/tdrop#28]
``Serial number of failed request:  1084
  Current serial number in output stream:  1084
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  1084
  Current serial number in output stream:  1084
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  1084
  Current serial number in output stream:  1084
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  1084
  Current serial number in output stream:  1084
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  1084
  Current serial number in output stream:  1084
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x5200001
  Serial number of failed request:  1084
  Current serial number in output stream:  1084``

Terminal is alacritty and using the sxhdrc config from the project description.
A window flashes and disappears before it can load

**Comment by noctuid** [comment]
I can't get alacritty successfully installed at the moment; I will try again later when I have time. If you can give me some information in the meantime, I can try to add support for it. I need to know the following:

1. What is the flag that alacritty uses for spawing a terminal and executing a command in it (most terminals use `-e <command>`)?

2. Do alacritty windows share the same PID? That is, if you open alacritty multiple times is there a new pid in the output of `pgrep alacritty` for each new terminal? Could you post the output of `pgrep -l alacritty`?

**Comment by noctuid** [comment]
Alacritty works fine for me without changes. If you were using `-s`, that may have been the problem. I've now added support for `-s` and `-a` in the `break` branch.

**Comment by ibrokemypie** [comment]
Sorry I never replied, must've forgotten and moved on. On master, tdrop and alacritty play well unless -s is used, which seems to result in ``$ ./tdrop -a -s dropdown alacritty
Command::spawn() failed: Permission denied (os error 13)``
Will try mentioned branch.
Sidenote, would you consider doing another tagged release at the current commit for packaging?

**Comment by ibrokemypie** [comment]
On the "Break" branch, running tdrop as tdrop -a -s dropdown alacritty seems to reset all other alacritty terminals, as well as spawns the dropdown near the center of the scree, however it changes slightly each time. Currently on i3wm

**Comment by noctuid** [comment]
What do you mean by reset? The problem may specifically be with the changes I made to the `-a` option for i3 on the branch (which I haven't tested yet). I will test with i3 when I get the chance; does the positioning issue happen with other terminals or just alacritty? Does it work correctly if you just use `-s`?

> would you consider doing another tagged release at the current commit for packaging?

I have a list of issues/features that I want to get to before tagging a release (afterwards I plan to package tdrop for nix).

**Comment by ibrokemypie** [comment]
@noctuid reset as in the terminals all clear completely and redraw, like typing reset.

**Comment by noctuid** [comment]
Is this still an issue? I cannot replicate this behavior on i3. What version of i3 are you using?

**Comment by ibrokemypie** [comment]
I no longer use alacritty, so I guess if it works for you and no one else has problems, this can be closed now, thanks

**Comment by noctuid** [comment]
Alright. A new issue can be opened if anyone else has problems with alacritty.
