### ISSUE TITLE
Add support for st / xst?

### ISSUE THREAD

**Issue by pellettiero** [noctuid/tdrop#29]
Hi, is it possible to add support for st (simple terminal) from suckless.org?
Should be pretty simple, according to the manpage (-g argument, X11 Geometry style)

Thanks!

**Comment by noctuid** [comment]
Have you tried tdrop with st/xst, and if so, what is the problem? It seems to be working for me. The problem might be related to the window manager. What window manager are you using?

**Comment by pellettiero** [comment]
bspwm. Do I need to add particular rules or commands to launch it?

Cheers!

**Comment by noctuid** [comment]
You should use the `-a` flag, but I'll probably need to add something to get it to work with st/bspwm. Could you give me your `xprop` output for an st terminal?

**Comment by pellettiero** [comment]
Sure.
```
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_LOCALE_NAME(STRING) = "it_IT.UTF-8"
WM_CLASS(STRING) = "st-256color", "st-256color"
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified size: 660 by 500
                program specified resize increment: 8 by 20
                program specified base size: 20 by 20
WM_CLIENT_MACHINE(STRING) = "devenv"
_NET_WM_NAME(UTF8_STRING) = "pellettiero: xprop"
WM_NAME(UTF8_STRING) = "pellettiero: xprop"
_NET_WM_PID(CARDINAL) = 1970
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
```

It doesn't seem to work with the `-a` flag, it only gives `child finished: error 256`

**Comment by noctuid** [comment]
I fixed it so that it will float st properly now with `-a`. The error is ignorable and shouldn't show up anymore.

**Comment by Uncleleech** [comment]
Hi sorry to comment on a closed issue but I'm having some problems with st & bspwm. Script works fine with urxvt but when I put st into the binding it gives the same error, opens the window for about 1/2 a second and immediately closes (im assuming with an error I cant see).

Thanks

**Comment by noctuid** [comment]
Just to confirm, is tdrop up-to-date? Also, could you post your exact tdrop command and the result of running `xprop` on an st terminal.

**Comment by Uncleleech** [comment]
```
_NET_WM_DESKTOP(CARDINAL) = 3
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLASS(STRING) = "st-256color", "st-256color"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 564 by 340
		program specified resize increment: 7 by 14
		program specified base size: 4 by 4
WM_CLIENT_MACHINE(STRING) = "neptune"
_NET_WM_NAME(UTF8_STRING) = "st"
WM_NAME(UTF8_STRING) = "st"
_NET_WM_PID(CARDINAL) = 16598
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
```
xprop.

tdrop is installed from tdrop-git in the AUR

**Comment by noctuid** [comment]
Could you post your tdrop command as well? Change it to redirect the output to a file and give me that output (e.g. `tdrop .... st &> ~/some-file`). Also, what is the output of `pacman -Q tdrop-git`?

**Comment by Uncleleech** [comment]
`tdrop-git 0.1.r105.g68f833a-1` pacman -Q output

`child finished with error '256'` st output

**Comment by Uncleleech** [comment]
hey, was just playing got a new error

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x2a00005
  Serial number of failed request:  69
  Current serial number in output stream:  69
```

**Comment by noctuid** [comment]
Just to check, does st work normally without tdrop? Also, are you using `xst-git`, and if not, which package are you using? The error message is the same as neeasade/xst#19, so it may be related.

**Comment by Uncleleech** [comment]
st works absolutely fine without tdrop.
I am not using xst-git I am using the st package from the arch repos.

**Comment by noctuid** [comment]
Those same packages are working fine for me. Unfortunately, I'm pretty much out of ideas for what is wrong. Can you try running `tdrop st` in a terminal?

**Comment by Uncleleech** [comment]
yep, that opens a terminal fine. Interesting.

**Comment by noctuid** [comment]
In that case, it's either a problem with your specific command or how it's being bound. Could you give me the full tdrop command with all the flags/options?

**Comment by Uncleleech** [comment]
`tdrop -a -w 1000 -s dropdown st`

just in case, the screen is more than 1000 wide

**Comment by noctuid** [comment]
Okay, it's a problem with st's `-e` flag (e.g. `st -e 'tmux attach-session -dt dropdown` doesn't work). I'm not sure if there is something that can be done about this, but I'll look into it.

**Comment by Uncleleech** [comment]
perhaps a way of using `-a` without tmux? just for the time being?

**Comment by Uncleleech** [comment]
Okay for the time being I'll just not use -s

**Comment by ninrod** [comment]
Hi, just would like to add some info: I'm using bspwm with xst-git from aur and this line is working fine for me: `tdrop -a -w 1362 "st -c scratchpad"`. 

I'd like just to be able to get a floating windows instead of a tiling one, but it's working fine as is.

thanks again for another wonderful program @noctuid.

**Comment by noctuid** [comment]
Please use the `-f` flag for program arguments; that is why your command is not working.

**Comment by noctuid** [comment]
It looks like this was a quoting issue after all (my bad). I've tested `-s` successfully with st-git and xst-git with the latest commit. Please let me know if you have any further trouble.

**Comment by kevindirect** [comment]
Using a oneshot rule works for me to create a floating bspwm dropdown st terminal:
`drop -ma -x '25%' -y '25%' -w '50%' -h '50%' -p 'bspc rule -a St -o state=floating' st`
