### ISSUE TITLE
Dual monitor layout

### ISSUE THREAD

**Issue by 97-109-107** [noctuid/tdrop#3]
First of all, thank you for this tool. It's been the best dropdown-terminal replacement I've come across. 

I have the following xrandrd layout:
  ![a](https://u.teknik.io/kwOoBA.png)

Using i3wm, when I invoke:
  ``tdrop -a -y 33% -y 18 -s desktop -n dropdown urxvt``

I get a terminal that spanning across two screens, similiar to the red rectangle drawn below:
  ![a](https://u.teknik.io/NqCdiK.png)

**Comment by angelic-sedition** [comment]
This is happening because the default width is 100%. A simple workaround would be to set the width to the size of the screen you want to use the dropdown on (`-w` or `--width=`). This is what I use for my dropdown. When I plug in another monitor, the width of the dropdown is slightly over the edge of the added monitor, but I haven't found it to be much of a problem.

If you want to use the dropdown on both monitors and setting the width makes the dropdown significantly too short or long on one of them, let me know. I could maybe add an option to set the width of the dropdown to a percentage of the width of the monitor it is being opened on

Also, you have two `-y`s in that command.

**Comment by 97-109-107** [comment]
Thank you for your reply.

Personally, I would be happy to see such a feature given that I move a lot between different screens. However, I can also see a way to circumvent this entirely by wrapping ``tdrop`` in a script that talks to ``i3wm`` asking for the current screen dimensions.

Looking through the dependencies I tried to figure out if any of the tools like ``xwininfo`` or ``xprop`` could provide a solution across all window managers. What I guess would be enough is to know which screen I'm at while running tdrop and the dimensions of it. 

Do you have any thoughts on that or pointers?

**Comment by angelic-sedition** [comment]
I'd really like to have a way to do this that isn't dependent on the window manager, but I don't think that is possible. You can get the dimensions of each monitor from `xrandr (-q)`, but you need to know the focused monitor as well. This is simple to get with bspwm. I'm not sure about i3; do you know of an i3-msg command to get the current monitor name (or dimensions)?

I might add support for just bspwm and i3, but I think this might be really ugly to do. It might be better left to a wrapper as you suggest. If I can find some way to get the current monitor's dimensions regardless of wm, I'll definitely add this option..

**Comment by 97-109-107** [comment]
If somebody would like to write a wrapper function, here's some code to get started: https://gist.github.com/97-109-107/a4b802197d8b5ca6f54e

As to answer your question, I've found the found (stolen) the following way of getting the name of the output and the size of it. https://gist.github.com/97-109-107/75865f024bf02365da74
It relies on ``jq`` as ``i3-msg`` output seems to be json only.

**Comment by angelic-sedition** [comment]
I think I will implement this next week when I have an extra monitor for testing (I don't have one right now). Knowing the name of the monitor is enough to implement this consistently at least in bspwm and i3. Can you tell me if the output name matches the monitor name in xrandr? This should be a pretty simple thing to do at least for these two window managers now; thanks.

I may consider a hacky solution using xwininfo if I can solve the instances in which it doesn't work. For example, what if there is no active window (desktop is empty)? Maybe I could spawn an invisible temporary window (if that's possible). Also, I would need some way to find out what monitors are where (what if there are 3+ monitors?); I don't remember if this is easily parsable from xrandr output (can't test it right now).

 Sorry for the late response; I've been quite busy this last week.

**Comment by 97-109-107** [comment]
Thank you for considering adding this. Yes, i3 uses the same output names as xrandr.
````
#!/usr/bin/env python
import i3
import subprocess

workspaces = [ws for ws in i3.get_workspaces()]
print(workspaces)

xrandr = subprocess.check_output("xrandr | grep \ connected", shell=True).decode("utf-8") 
print(xrandr)
````

I took some steps towards the wrapper function which we discussed earlier:
````
#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
import i3
import re
import subprocess

#how tall the dropdown should be, in percentages
percentage = 33;
#assuming you have a top bar, how many pixels is it?
top_offset = 18;

def getCurrentScreen():
    workspace = [ws for ws in i3.get_workspaces() if ws['focused']][0]

    screen_w =str(workspace['rect']['width'])
    screen_h =str(workspace['rect']['height'])

    return int(screen_w), int(screen_h);

screen_w, screen_h = getCurrentScreen();
screen_h = int(screen_h * percentage/100);
xwininfo = subprocess.check_output("xwininfo -id $(xdotool getactivewindow)", shell=True).decode("utf-8") 

x_regex = re.compile(r'Absolute upper-left X:\s+(\d+)', re.MULTILINE)
y_regex = re.compile(r'Absolute upper-left Y:\s+(\d+)', re.MULTILINE)

x_offset = x_regex.findall(xwininfo)[0]
y_offset = int(y_regex.findall(xwininfo)[0]) + top_offset

print(x_offset, y_offset, screen_w, screen_h)
command = "tdrop -a -w {w} -h {h} -x {x} -y {y}  -y 18 -s desktop -n dropdown urxvt".format(w=screen_w, h=screen_h, x=x_offset, y=y_offset)

subprocess.call(command, shell=True)
````

However, I've hit a wall somewhere, can't quite remember where it was.

**Comment by noctuid** [comment]
This is working for me with bspwm. I haven't gotten the chance to test it with i3 yet. Right now, it requires that there be an active window before calling the dropdown. As soon as I can, I'll change it so that it will wait for the dropdown to be opened and use it as the active window to determine the monitor when necessary. A bit hacky but not as bad as I thought it might be. I think it should work consistently even with different monitor setups.

**Comment by 97-109-107** [comment]
Thanks for the update! Upon testing it with the following command:
``tdrop -a -h 33% -y 18 -m -s desktop -n dropdown urxvt;``
I observed the following:
- First launch on smaller screen (leftmost), tdrop is positioned and sized correctly
- Reran the command while focused on the other, bigger (rightmost) screen, tdrop appears on the former screen, retaining it's size
- Killed the tdrop-bound urxvt instance
- Launched tdrop on the rightmost screen, tdrop is as big as it'd need to be, but positioned on the leftmost screen.
- Reran the command on the left screen, tdrop appeared unchanged.

**Comment by noctuid** [comment]
I didn't anticipate that other window managers would act this way. With bspwm, floating windows are automatically set within the current screen. The fix should (hopefully) be simple.

**Comment by noctuid** [comment]
Tell me if that fixes things. The one thing I am confused about is that you say that it is not the correct size in the second bullet. 

If there is an issue with the sizing, could you give me the output of `xrandr` as well as the output of `xwininfo -id $(xdotool getactivewindow)` for the window you have focused on the second monitor before attempting to show the dropdown?

**Comment by 97-109-107** [comment]
It works! Thanks for fixing this!

**Comment by noctuid** [comment]
@97-109-107 Great! Let me know if you have any other problems.

**Comment by noctuid** [comment]
@97-109-107 Actually there is one more problem. Can I get you to explain the behaviour of i3 with multiple monitors to me? If you create the dropdown on monitor 1 hide it, and then press the dropdown key on an empty monitor 2, the dropdown appears on monitor 1 instead, correct? If you just open a window normally on an empty monitor 2 (I guess I mean a tiled window), will it appear on monitor 2 though? Does your i3 layout have a separate desktop/workspace on each monitor?

If i3 acts like this, I'll need to spawn something on empty monitors to use xwininfo...

**Comment by 97-109-107** [comment]
It would be easier for me to describe it this way:
Desktops are bound to a monitor unless you press a key to send them to the other screen.
If you have screens S1 and S2 and Desktops D1, D2, D3 in the following layout:
- S1: D1, D2
- S2: D3
And ask i3wm to focus on D1 while being on S2 - it will shift the focus to the other screen.
I hope this is clear enough. Let me know if I can clarify it any better for you.

*I have another issue which might or might not be directly related to this functionality - I will open a new issue for it.*

**Comment by noctuid** [comment]
Okay that makes sense (and I got multiple monitors working with i3). I just need to decide now whether I should bundle tdrop with a c progam to create an empty window or add a optional dependency for a simple program like xclock or something. Neither seem like very good ideas. I'm just going to leave this open for now until I figure that out.

**Comment by 97-109-107** [comment]
btw, if you ever need to test tdrop with weird wms, this might be useful in a virtual machine: http://linuxbbq.org//

**Comment by noctuid** [comment]
@97-109-107 Thanks! That looks pretty cool.

Also, I am going to fix things so that if i3 (or bspwm) is the window manager, it won't use the hacky xwininfo stuff and will work if the workspace is empty. I don't really want to add jq as a dependency, so I just used a slightly ugly awk command. I just want to test it first (the next time I can connect to another monitor).

**Comment by noctuid** [comment]
`-m` now will use the dropdown (instead of creating some other random window) to determine the current monitor on empty desktops for WMs other than bspwm and i3. I think I've fixed all generic problems with the option. Any WM specific issues can go in new issues.

**Comment by 97-109-107** [comment]
This definitely made things more snappy and realiable, thanks!
As for the dual-monitor not-aligned issue I will have to remember to check that again and report back.
