### ISSUE TITLE
tdrop does not work on alacritty 0.7.1

### ISSUE THREAD

**Issue by zjuyk** [noctuid/tdrop#302]
# Environment

PC: gentoo
tdrop: 0.3.0
alacritty: 0.7.1

# Description

When I  update alacritty version to 0.7.1, the tdrop can not work to dropdown alacritty.
I can find the running tdrop process using `ps aux | grep tdrop`.

Addition: kitty work well with tdrop, so I think there is something wrong between alacritty 0.7.1 and tdrop 0.3.0

**Comment by zjuyk** [comment]
I run `tdrop -ma -w 900 -y 28 -x 510 -h 40% -n 1 alacritty` in the terminal, get error message as

```
error: Found argument '-d' which wasn't expected, or isn't valid in this context
```

The `-d` parameter may be expired

**Comment by thevtm** [comment]
I believe this https://github.com/alacritty/alacritty/commit/07684281901b8d287221ade9b7c93a0f437a26f1 was the change that broke it.

They've removed the commands  `--dimensions` and `--position` in favor of:

```
alacritty --option window.position.x=32 window.position.x=64 window.dimensions.columns=99 window.dimensions.lines=55
```

**Comment by thevtm** [comment]
It's working on `master` for me.

**Comment by zjuyk** [comment]
Thank you
