### ISSUE TITLE
PopOS tiling

### ISSUE THREAD

**Issue by Jarvvski** [noctuid/tdrop#307]
Either I'm missing something, or this doesn't seem to work with the tiling built into PopOS gnome desktop

I'm using

```sh
tdrop -m -a -w "100%" -y "$PANEL_HEIGH" kitty
```

But it just tiles the newly spawned window regardless

**Comment by Jarvvski** [comment]
For anyone else that comes across this, you can solve it by changing the class or title of your new window via positional arguments

```sh
tdrop -m -a kitty --class "tdrop"
```

> Kitty supports changing the class via `--class`

Then, in `~/.config/pop-shell/config.json` you can setup a config-base rule to float the window:

```json
{
  "float": [
    {
      "class": "tdrop"
    }
  ],
}
```

**Comment by noctuid** [comment]
Yeah, unless there is a shell command that can be used instead of the config to float only the next spawned window of a class or to float the current window, users will have to use that config file.
