### ISSUE TITLE
xiate support

### ISSUE THREAD

**Issue by ibrokemypie** [noctuid/tdrop#31]
hey, would you consider adding support for xiate?
https://github.com/vain/xiate
thatd be awesome, currently it doesnt seem to work, thanks!

**Comment by noctuid** [comment]
Xiate is now working correctly for me on the break branch.

**Comment by ibrokemypie** [comment]
On i3, using ``bindsym Control+grave exec ~/tdrop/tdrop -a ~/dotfiles/.xiate/xiatec`` as my bind, xiate simply gets spawned infinitely as a tiled window, and does not hide/restore. Am I doing something wrong?

**Comment by noctuid** [comment]
Tdrop does not support the program argument being a path currently. Put `xiatec` in your PATH and try `-a xiatec`.

**Comment by ibrokemypie** [comment]
Alright that works, though it seems to have weird placement, appearing anywhere on the screen the first time, then eventually centering over the next few tries. Any way to force it to be at the top as a dropdown on i3?

**Comment by noctuid** [comment]
It should be fixed now. Let me know if you have any other problems.

**Comment by ibrokemypie** [comment]
Closer, however it spans both monitors, is there any way to only be the width of the currently foccussed workspace?

**Comment by noctuid** [comment]
`-m` should do this.
