### ISSUE TITLE
herbstluftwm now supports window floating 

### ISSUE THREAD

**Issue by t-wissmann** [noctuid/tdrop#316]
In the recent versions of herbstluftwm (since v0.8.0), single window floating is supported, so there is no reason to set the terminal window to fullscreen (in `post_float()`). Similarly to bspwm, you can add a window rule before starting the terminal emulator in `pre_float()`:
```bash
herbstclient rule class="$class" floating=on
```

**Comment by noctuid** [comment]
Is there an equivalent of bspwm's oneshot rule (only float the next created window that matches)? If not, I think the user should just run their rule and not use `-a` with tdrop.

**Comment by t-wissmann** [comment]
Yes, there is, it is indicated by `once`, which will remove a rule as soon as it matches:
```
herbstclient rule once class="$class" floating=on
```
This rule will be removed automatically as soon as a window with class `$class` appears.

**Comment by t-wissmann** [comment]
Thanks :-)

The current window is floating if the following command has exit-status 0:
```
herbstclient or , compare tags.focus.floating = on , compare clients.focus.floating = on
```
(hlwm supports setting an entire tag('virtual desktop') to floating, so it is not sufficient to check clients.focus.floating.)

The monitor thing is not easy however, because the hlwm monitors are independent from the X outputs (so you can split large screens into smaller logical monitors). What do you need the monitor name for?

If you need the monitor's coordinates then the command `herbstclient monitor_rect` prints the x, y, width, and height of a monitor, e.g.:
```
$ herbstclient monitor_rect 
0 0 2560 1440
```

**Comment by noctuid** [comment]
Thanks! I've added full support for herbstluftwm.

**Comment by t-wissmann** [comment]
Thanks!
