### ISSUE TITLE
next tagged release

### ISSUE THREAD

**Issue by TeddyDD** [noctuid/tdrop#324]
I'd like to update Void Linux package to the newest version (without Alacritty workaround) but I need tagged version. Would you be so kind and tag next release? :) 

Also: what the heck is going on in the issues :eyes:

**Comment by noctuid** [comment]
Sorry about the spam and late response. I've fixed some things and tagged 0.4.0. If there are any issues, I will tag a 0.4.1.

**Comment by TeddyDD** [comment]
Thanks :+1:
