### ISSUE TITLE
--class ineffective [xfce4][gnome-terminal]

### ISSUE THREAD

**Issue by michja** [noctuid/tdrop#33]
Hey noctuid,

I'm finding that gnome terminal in xfce4 will always have the class set to Terminal despite using --class 'whatever' arg. 
Any ideas?

Cheers,
Michael

**Comment by noctuid** [comment]
`--class` is not supposed to change the class of a window. It is meant to let tdrop know the class of a window for use with floating rules (only useful for bspwm currently). I've updated the documentation to make this more clear.

**Comment by michja** [comment]
Haha right, that'll be why then. I had a look through the code and it didn't make sense with my understanding of the function of --class. I need a way to write a compton rule to show tdrop windows instantly (no fade). Have forked and added --name -> xdotool set_window --name. Please use this code/idea if its useful.
Cheers

**Comment by noctuid** [comment]
Sure, I can add that functionality. You can also use one of the hooks to do this currently (`--create-hook "xdotool set_window --name <name>

**Comment by michja** [comment]
Cool. I didn't realise that was possible. Keep up the good work

**Comment by noctuid** [comment]
I've added a dedicated `--name` option.

**Comment by imsamuka** [comment]
I hoped that the `--class` option would allow to change it out of the box, but if using _xdotool_ `--class` and `--classname` options allow it, that's a good workaround

It's useful when running different applications with tdrop (with different `names`) but all of them inheriting the same `class`, then creating only one set of rules in the Window Manager for said `class`
