### ISSUE TITLE
Always on top hook with shortcut

### ISSUE THREAD

**Issue by amirhaouala** [noctuid/tdrop#334]
I'm using Arch, what is the command that I should run if I want alacritty to always stay on top, thanks

**Comment by noctuid** [comment]
See the [example in the readme](https://github.com/noctuid/tdrop#hooks). Assuming wmctrl works for your window manager, you can used the `-P` flag or maybe the `-C` flag: `tdrop -P 'wmctrl -i -r $wid -b add,above'....`

**Comment by amirhaouala** [comment]
THANKS I got the behavior I want, how do I get the behavior like in instantOS terminal ( or the terminal in the gif that opens up in the center with border ), system info : the operating system I'm on is Opensuse Tumbleweed with KDE as window manager and krohnkite extension for kwin

**Comment by noctuid** [comment]
I'm not familiar with the instantOS terminal. Can you more specifically describe the behavior you want and what tdrop command you tried?

**Comment by amirhaouala** [comment]
in the middle of the screen like in the gif used for this repo

**Comment by noctuid** [comment]
I'm not sure what you want. The dropdown is at the top in the gifs, and I believe the gifs are just using the default geometry settings.

**Comment by amirhaouala** [comment]
I meant the middle of the screen like a centered box apparently in the gif that happened just when the terminal was loading

**Comment by noctuid** [comment]
If you use percentages, you can center. Something like `tdrop -y 25% -h 50% <terminal>`
