### ISSUE TITLE
Dropdown placement incorrect with -m flag and no windows on desktop

### ISSUE THREAD

**Issue by Barbarossa93** [noctuid/tdrop#335]
Hey there,

When I use this command `tdrop -m -w 69% -h 60% -x 15% -y 74 -s Dropdown urxvt -name dropdown`, the placement of the window is near the bottom of the screen if there are no open windows on the desktop. When at least one window is opened, the window is placed correctly. Removing the `-m` flag, the window is in the correct place, except when using a multi-monitor setup, the window is stretched across both monitors.

Herbstluftwm is my window manager.

**Comment by Barbarossa93** [comment]
Interestingly, if I include the new `-A` activate flag, the window moves to the correct position after hitting the keybinding again. A partial solution I suppose

**Comment by noctuid** [comment]
There is separate logic for getting the monitor geometry when there are no open windows. I will look into why this fails on herbstluftwm (maybe it needs to wait for the dropdown to be open). For herbsluftwm, it looks like I can just get the monitor geometry directly (#316), so it should not be difficult to fix.

**Comment by noctuid** [comment]
I'm not sure how it was ever giving you the right position before. I had never merged the herbstluftwm branch, and before tdrop would just make windows fullscreen for herbstluftwm. It should work now with both `-a` and `-m`.
