### ISSUE TITLE
kitty sticks to top left of screen on kde

### ISSUE THREAD

**Issue by BLucky-gh** [noctuid/tdrop#337]
so I use tdrop with kitty do have sort of a quake dropdown terminal with `tdrop -ma -w 90% -h 70% -y "$height" -x 5% kitty --name "dropdown" --config ~/.config/kitty/kitty-drop.conf`, which put the window in the middle before but now kitty is stuck to the top left of the screen regardless of the -w flag's value

**Comment by BLucky-gh** [comment]
update: now it randomly switched to bottom left for no apparent reason, so I suspect the reason is that kde decided to snap new windows to the least cluttered corner, though that hasn't been an issue before so I'm not sure

**Comment by noctuid** [comment]
Can you try running xdotool's windowmove command in the terminal, e.g. `xdotool getactivewindow windowmove 10 10`? If it doesn't let xdotool move the window, there is nothing I can do.

**Comment by BLucky-gh** [comment]
Unfortunately not anymore since in the year since I've opened this issue I have moved and switched jobs and have to use windows at the new workplace, thus I don't have a device to replicate it on

**Comment by noctuid** [comment]
Okay, if you start using KDE again with tdrop and have this issue, let me know, and I will reopen.
