### ISSUE TITLE
Where'd my window go?

### ISSUE THREAD

**Issue by eater** [noctuid/tdrop#338]
I am running i3. I had a tiled gvim instance and I used `tdrop current` to hide it. Then, while it was visible, I used `tdrop --clear current` to clear it. The window vanished and it doesn't appear in the output of `wmctrl -l` but I can see the process is still running ... somewhere.

How can I get it back?

**Comment by eater** [comment]
Xdotool can see it but can't make it appear.

```
$ xdotool search --name "GVIM2"                                                          
339738627
$ xdotool windowactivate 339738627                                                              
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
$ xdotool windowmap 339738627
$ xdotool windowraise 339738627
$ xdotool windowfocus 339738627
```

**Comment by noctuid** [comment]
This sounds like a problem with xdotool or something besides tdrop. `--clear` only writes to a file, and if xdotool can't map the window, something else must have gone wrong. Can you replicate this?

**Comment by eater** [comment]
I can indeed replicate it! I have xdotool version 3.20160805.1 for what it's worth.

**Comment by noctuid** [comment]
I don't think it will help to update, but there have been a few xdotool releases releases in the past month. Just to clarify, gvim disappears when you run `tdrop --clear current`? Also, can you confirm the window id beforehand with `xdotool selectwindow` and try to map that afterwrads in case the search is returning an incorrect window id? The output of `xwininfo -id <wid>` might be helpful.

**Comment by eater** [comment]
`$ xwininfo -id 339738627                                                                                                                                      [14:07:23] gen

xwininfo: Window id: 0x14400003 "+ sxhkdrc - GVIM2  "

  Absolute upper-left X:  960
  Absolute upper-left Y:  54
  Relative upper-left X:  960
  Relative upper-left Y:  54
  Width: 950
  Height: 1014
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +960+54  -10+54  -10-12  +960-12
  -geometry 93x48-10-12
`

**Comment by eater** [comment]
I figured out that if I first `xdotool unmap` the (supposedly already unmapped) window and then `xdotool map` it, I can get it back.
