### ISSUE TITLE
toggle window size &/or location

### ISSUE THREAD

**Issue by vapniks** [noctuid/tdrop#340]
It would be nice to have to option of also toggling window size like guake.

For the benefit of others who also desire this behaviour here is the link to a zsh script I wrote to do this: https://github.com/vapniks/toggle_window_geometry
(you can bind calls to the script to keybindings just like you do with tdrop).

**Comment by noctuid** [comment]
This is outside the scope of tdrop. A separate script like yours should be used for cycling sizes.
