### ISSUE TITLE
does tdrop work in xwayland?

### ISSUE THREAD

**Issue by dreamcat4** [noctuid/tdrop#341]
Hello,
does tdrop work in xwayland?

Am wondering if anybody out there has tried this yet? Because if it can in this way then it would be pretty helpful stopgap. Between now and however long it would take for something like tdrop to work natively.... don't have any specific expectations here either way! ...it just would be helpful and maybe xwayland does already support at least some of the necessary x11 based helper tools? IDK

And of course there are alternative ways for setting up an appropriate keybindings. But that's nothing to do with `tdrop` itself. And we already have some working solution(s) for that side of it

**Comment by Qgel** [comment]
tdrop works fine for me on xwayland. You just need to make sure you are actually running the application you want to control under xwayland by unsetting `WAYLAND_DISPLAY`, e.g.:
```
WAYLAND_DISPLAY= tdrop -mta -s drop alacritty
```
