### ISSUE TITLE
Some programs don't float in herbstluftwm

### ISSUE THREAD

**Issue by pyDeamon** [noctuid/tdrop#346]
Hi
I have tried tdrop with some programs and I have some problems. 

Though, It works well and as expected with kitty terminal. 
With emacs, pcmanfm and speedcrunch, the windows are tilied pushing other windows, but the toggling works fine.
for thunar, the window don't toggle at all.

I am using herbstluftwm version 0.9.3 with tdrop -a flag.

**Comment by noctuid** [comment]
This is probably fixed in the feature/remember branch. I will look into finishing/merging it when I have time. You can also use that branch temporarily for now. I may need to add explicit support for thunar.

**Comment by noctuid** [comment]
This should be fixed now. Please update and let me know if it still happens.
