### ISSUE TITLE
xprop: Invalid window id format

### ISSUE THREAD

**Issue by robinsrk** [noctuid/tdrop#360]
When starting todoist app from terminal with tdrop, it shows "xprop: Invalid window id format" error. 

And can't use tdrop to show hide the app. 

![image](https://user-images.githubusercontent.com/50480143/178660460-5a71eb14-ced2-42e8-9ef5-d7db7948e78c.png)

The package in arch linux is "todoist-appimage"

**Comment by noctuid** [comment]
Please try now.
