### ISSUE TITLE
tdrop windows gain focus only after running tdrop -A twice

### ISSUE THREAD

**Issue by Schweber** [noctuid/tdrop#366]
I am using NixOS 22.05 with Kwin 5.24.5 and tdrop 0.4.0. The dependencies of tdrop are all installed and available in the terminal.

I want to use e.g. `alacritty` as a fullscreen drop down like `yakuake`. In order to have it come up as intended, i have to use the following settings, because i also use `krohnkite` as a tiling window script for Kwin:

`tdrop -Aam -w 100% -h 100%  alacritty`

<img width="752" alt="image" src="https://user-images.githubusercontent.com/64630479/196870924-75dbc95e-a541-4c1f-ba5d-47f9720239dc.png">

This brings up the alacritty window fullscreen on top of everything else (as intended), but it doesn't have focus until i run the tdrop command **again**. If i run it a third time, the window is hidden as intented.

Without the `-A` flag it doesn't gain focus on the first run and running the command again just hides the window.

What can i do to have the window opened by tdrop gain focus without having to run the command **twice** with the `-A` flag?

**Comment by noctuid** [comment]
Can you first update tdrop and confirm this issue still happens?  0.4.0 is very old.

**Comment by Schweber** [comment]
Sorry, that might be it. I'm no longer running KDE so i can't test it anymore.

The issue with Firejail persists in 0.5 though.
