### ISSUE TITLE
bspwm. tdrop opens the application on wrong desktop (bspc-monitor)

### ISSUE THREAD

**Issue by peskovdev** [noctuid/tdrop#369]
In order to reproduce this bug, do the following:
1. Twice execute (open & close) on particular bspc-monitor: `tdrop -am -h 60% -w 50% -y 25 -x 25% app`
2. Change bspc-monitor
3. Execute `tdrop -am -h 60% -w 50% -y 25 -x 25% app` again for opening on NEW monitor
4. You will be thrown to the previous monitor, and app will be open there

You can see example [here](https://youtu.be/c-h0TWy8rcQ)

**Comment by devpeskov** [comment]
I think there should be the following logic: 
1) if we are on the desktop on which the application is open - it must be closed
2) if we are on a desktop on which the application is not open - it must either be opened (if it wasn't created), or moved to the new desktop (from previous)

Now, when you close the window, tdrop remembers the desktop number and tries to open the application THERE the next time you call it. Why?

**Comment by devpeskov** [comment]
![image](https://user-images.githubusercontent.com/56066655/200166818-234e6e60-4da7-4a54-90fc-5e9b966ad6d1.png)
I found decision: you should to delete or comment 457 line of script

Author said about this: "windowmap does not activate for all window managers"
But in my case, without this line - everything is OK. Perhaps the author added this option to make tdrop work on little-known wm. But it broke script on bspwm.

**Comment by devpeskov** [comment]
I created a pull request for fix this: https://github.com/noctuid/tdrop/pull/370

**Comment by noctuid** [comment]
I will investigate if there is some more generic solution.  If not, I will merge your PR. Thanks!

**Comment by peskovdev** [comment]
Hi! How’s the progress with the solution? I would be glad to merge my PR. Thanks!

**Comment by noctuid** [comment]
Ping me in a week again if I haven't looked into it yet.

**Comment by noctuid** [comment]
>  But in my case, without this line - everything is OK. Perhaps the author added this option to make tdrop work on little-known wm. But it broke script on bspwm.

Just for context, I was using bspwm at the time and this was intended to fix this issue for bspwm.  I can't reproduce the issue on bspwm 0.9.10.  Does it happen every time or inconsistently?  Made some sleep time is needed for bspwm.

What version of bspwm are you on?  If I use #370, it no longer works correctly for me on bspwm (the dropdown shows up but is not focused).

**Comment by peskovdev** [comment]
Yes, with every program that i tried.

**Comment by peskovdev** [comment]
> Could you link me to your config or post it here?

Yes, of course! I've just published it: https://github.com/peskovdev/dotfiles

**Comment by noctuid** [comment]
Is your bspwmrc there somewhere (or do you not have one)?  I didn't see it.  My only guess right now for why this happens for others but not me is some difference in settings.

Also, what does `xdotool --version` report?

I have a few suggestions you can try:

1. Add `--sync` after every windowmap in `map_and_reset_geometry`, e.g. `xdotool windowmap --sync "$wid" 2> /dev/null` (this would be the ideal solution if it works).

2. Try replacing "windowactivate" with "windowfocus"

3. Try adding sleep time:

```bash
# increase sleep time if it still doesn't work
sleep 0.05
xdotool windowactivate "$wid" 2> /dev/null
```

**Comment by peskovdev** [comment]
I have separated config, so my bspwmrc on [another branch](https://github.com/peskovdev/dotfiles/blob/home/bspwm/.config/bspwm/bspwmrc). If you would like to see not separated config, it's my [friend's config](https://github.com/exynil/dotfiles), we tested this bag on his computer, and there are the same problem.

xdotool version: 3.20211022.1

And about suggestions, I'll try this steps a little bit later, ty

**Comment by CUexter** [comment]
is there any update on this issue, i tried @peskovdev fixed but it didnt work for me

**Comment by peskovdev** [comment]
> is there any update on this issue

Sorry for the delay.
Yeah, I have checked, and with `--sync` flag it works pretty well!

Also, I have updated the PR. I think we can close this issue.

**Comment by noctuid** [comment]
Thanks all!

**Comment by yaaama** [comment]
> > is there any update on this issue
> 
> Sorry for the delay. Yeah, I have checked, and with `--sync` flag it works pretty well!
> 
> Also, I have updated the PR. I think we can close this issue.

This worked!
I guess the Arch repositories have not updated the package there.

I just wanted to make the solution clear for those that have not got the updated package:

1. Go into wherever the `tdrop` program is stored (you can use `whereis tdrop` command to find it).
2. Open up the script, and replace find the function `map_and_reset_geometry` with this new definition:

```sh
map_and_reset_geometry() {
	if [[ -n $width ]] && [[ -n $height ]] && [[ -n $xoff ]] \
		   && [[ -n $yoff ]]; then
		xdotool windowmap --sync "$wid" windowmove "$wid" "$xoff" "$yoff" \
				windowsize "$wid" "$width" "$height" 2> /dev/null
	elif [[ -n $width ]] && [[ -n $height ]]; then
		xdotool windowmap --sync "$wid" windowsize "$wid" "$width" "$height" \
				2> /dev/null
	elif [[ -n $xoff ]] && [[ -n $yoff ]]; then
		xdotool windowmap --sync "$wid" windowmove "$wid" "$xoff" "$yoff" \
				2> /dev/null
	else
		xdotool windowmap --sync "$wid" 2> /dev/null
	fi
	# windowmap does not activate the window for all window managers;
	# windowactivate should be run separately after windowmap --sync or it can
	# activate a window on another desktop on some window managers (e.g. bspwm)
	xdotool windowactivate "$wid" 2> /dev/null
}
```


3. Save and close the file.
4. You can try rerunning the tdrop and seeing whether it has fixed the problem.
