### ISSUE TITLE
Hotkey is not always showing terminal on top of other windows

### ISSUE THREAD

**Issue by roorco** [noctuid/tdrop#37]
I'm using tdrop with termite, I have an hotkey that fire this command: tdrop -ma -w -4 -s dropdown termite, my system is Manjaro 17.
Tdrop is working most of the time, but sometimes my terminal appears behind other windows.
So if I have a fullscreen window I just can't see the terminal.
Then if I launch the terminal again it eventually reappears on top of other windows.

**Comment by noctuid** [comment]
This sounds like it could be an xdotool bug (or a WM bug). Can you give me some more details? Does this happen randomly? Does this only happen in fullscreen? Will the dropdown ever show on top in fullscreen? 

What window manager are you using? Please post the output of the following:
```shell
xprop -notype -id "$(xprop -root -notype | \
	awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" \
	-f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1

```

Try adding `-P 'xdotool windowactivate $wid'` to your tdrop command. Does this fix the issue?

**Comment by roorco** [comment]
```
$ wmctrl -m
$ Mutter (Muffin) 
```
Same  answer from the command you provide me.
But adding `-P 'xdotool windowactivate $wid'` it seems it solved the problem.
So my complete command for the hot key is: 
`tdrop -ma -w -4 -P 'xdotool windowactivate $wid' -s dropdown termite`
