### ISSUE TITLE
Does tdrop work with DWM?

### ISSUE THREAD

**Issue by Maritsu** [noctuid/tdrop#375]
I'm using DWM 6.4 and was looking into this project, however upon installing and testing it, the new terminal emulator instance (in my case Alacritty, which is mentioned to work in the README) appeared as a normal tiled window instead of a floating one. I have the floating layout enabled (as in, available as one of the options when switching between layouts) and thought I should open an issue. Am I doing something wrong or does tdrop not work with DWM?

Command used:
```tdrop -a -m -w 60% -h 30% alacritty```

**Comment by noctuid** [comment]
I've never used DWM, but tdrop does not do anything special to try to float windows on dwm.  It will just spawn the terminal the same as if you ran `alacritty` yourself.  You'll have to handle floating rules yourself (e.g. see #108).

**Comment by Maritsu** [comment]
Oh alright, tyvm, will look into it!
