### ISSUE TITLE
Trouble with -f flags

### ISSUE THREAD

**Issue by HaoZeke** [noctuid/tdrop#39]
# Bug Report

As per the manual, I have the following in my `sxhdrc`:

```bash
F1
 tdrop -p "bspc rule -a kitty -o state=floating" -ma -w 70% -h 70% -x 15% -y 15% -n 1 -s mainWindow kitty '-f "--config $USER/.config/kitty/kittyMain.conf"'

```

However this is not respected by the program (`kitty`).

I can confirm that it runs as expected from the terminal (without `-f` of course).

Is there something I'm missing?
Any further information I could provide?

### Basic info

``` bash
# Version
aur/tdrop-git 0.1.r23.g682ec14-1 [installed: 0.1.r142.g8808dff-1]
```

**Comment by noctuid** [comment]
`-p` should not be necessary with `-a`, and the `-f` itself should not be inside single quotes (only the argument). Does making that change fix the issue for you?

**Comment by HaoZeke** [comment]
Surprisingly the following runs the program, but still doesn't pick up the configuration:

```bash
F1
 tdrop -p "bspc rule -a kitty -o state=floating" -m -w 70% -h 70% -x 15% -y 15% -n 1 -s mainWindow -f '--config $USER/.config/kitty/kittyMain.conf' kitty 
```

**Comment by noctuid** [comment]
As specified in the manpage, the program must be the last argument. You should also use double quotes instead of single quotes if you want to use an environment variable (and are you sure that you don't want to use `~` or `$HOME`?).

I'll look into `-a` not working. Does `bspc rule -a \*:"kitty" -o state=floating` not work for you? I'm on bspwm 0.9.2 currently; hopefully the rule class syntax did not change again.

**Comment by HaoZeke** [comment]
Thanks a ton for the help, that got it working

```bash
F1
 tdrop -p "bspc rule -a kitty -o state=floating" -m -w 70% -h 70% -x 15% -y 15% -n 1 -s mainWindow -f "--config $HOME/.config/kitty/kittyMain.conf" kitty 
```

Oddly, I can replace `bspc rule -a kitty -o state=floating` with `bspc rule -a \*:"kitty" -o state=floating` without any change (i.e, it works)

`-a` still tiles it though.

**Comment by noctuid** [comment]
Great, I made a new issue for the `-a` problem (see #40).
