### ISSUE TITLE
the spotify client won't toggle

### ISSUE THREAD

**Issue by amtoine** [noctuid/tdrop#390]
hello there :yum: :wave: 

i'm having some trouble making `tdrop` and `spotify` work together :open_mouth: 

## what happens
i open `spotify` from `tdrop`, it works just fine :ok_hand: 
```bash
> tdrop spotify
2022-12-31 12:02:40 Debug command: tdrop spotify
/usr/bin/tdrop: line 892: /tmp/tdrop_amtoine_:0/auto_hidden/wid: No such file or directory
[libprotobuf ERROR ../core/vendor/protobuf3/src/google/protobuf/wire_format_lite.cc:577] String field 'spotify.event_sender.proto.DroppedEvents.DroppedEventsBySequenceIdEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
# spotify started and plays music
```
i try to hide the window, it only makes the window black and stays there
```bash
> tdrop spotify
2022-12-31 12:02:50 Debug command: tdrop spotify
# the window is still there with a black background
```
`spotify` then comes back as normal
```bash
> tdrop spotify
2022-12-31 12:02:53 Debug command: tdrop spotify
# spotify is back as normal
```

in the end, the window nevers goes away, only the "image" inside it, toggling between the normal `spotify` look and a black screen

## `spotify` installation
i installed `spotify` on ArchLinux with `snap`
```bash
> spotify --version
Spotify version 1.1.84.716.gc5f8b819, Copyright (c) 2022, Spotify Ltd
```
and in `nushell`
```bash
> snap list | detect columns | where Name == spotify
WARNING: There is 1 new warning. See 'snap warnings'.
╭───┬─────────┬──────────────────────┬─────┬───────────────┬───────────┬───────╮
│ # │  Name   │       Version        │ Rev │   Tracking    │ Publisher │ Notes │
├───┼─────────┼──────────────────────┼─────┼───────────────┼───────────┼───────┤
│ 0 │ spotify │ 1.1.84.716.gc5f8b819 │ 60  │ latest/stable │ spotify** │ -     │
╰───┴─────────┴──────────────────────┴─────┴───────────────┴───────────┴───────╯
```

## `tdrop` installation
```bash
> pacman -Q | grep tdrop
tdrop 0.5.0-1
```

## my window manager
```bash
> bspwm -version
0.9.10
```

**Comment by noctuid** [comment]
It should be fixed now.  I tested with the aur version but had the same issue.  Let me know if there is still a problem.

**Comment by amtoine** [comment]
> It should be fixed now. I tested with the aur version but had the same issue. Let me know if there is still a problem.
>
fair enough, i had to replace `tdrop` with `tdrop-git` to have access to the latest commit :smirk: 

but that works like a charm :relieved: 
thanks a lot @noctuid :heart:
