### ISSUE TITLE
 -a not working correctly on bspwm 0.9.3

### ISSUE THREAD

**Issue by noctuid** [noctuid/tdrop#40]
Reported in #39.

`-a` is working correctly for me with `bspwm-git` (EDIT: and with the release version `0.9.3`) and kitty. Since you say that floating command works for you, I'm wondering if the window manager is not being detected properly. Does it work if you add `--wm bspwm` to the command? What is the output if you run the following command?

```
xprop -notype -id "$(xprop -root -notype | \
	awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" \
	-f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1
```

**Comment by HaoZeke** [comment]
Yup, that fixed it.. `--wm bspwm` I mean..
So now it floats correctly, without the `-p` option.
For some odd reason my `xprop` output is `LG3D` (for some Java fix I believe).

Thanks!

**Comment by noctuid** [comment]
Ah right, that's a common configuration for some tiling window managers (`wmname LG3d`); I'll add a note about that to the readme.
