### ISSUE TITLE
Workaround to fix apps spalsh screen getting in the way.

### ISSUE THREAD

**Issue by jediaxe** [noctuid/tdrop#401]
Hello. Thank you for making this wonderful tool. its genius and a must have!

Is there a workaround to fix dropdown not working when apps launch with a splash screen? I usually fix this by launching with a --no-splash option but some apps don't have that option available.
would post hooks be useful in this case?

**Comment by noctuid** [comment]
Unfortunately, it currently will have to be handled differently on a per-app basis inside tdrop.  Please open issues for any specific programs where this is a problem.
