### ISSUE TITLE
How to launch a program hidden?

### ISSUE THREAD

**Issue by Schweber** [noctuid/tdrop#402]
I am using awesomewm and would like to load tdrop windows of my most used programs on startup **hidden,** so that they appear immediately when i hit their shortcut and don't have to load when invoking their shortcut for the first time in the session.

However, i didn't find an option in tdrop to load a program in the background. Standard behaviour is to show the window on launch and i would like to tell tdrop not to show the window on launch, as if i had launched the program and then run the command again to hide it e.g. as if running "tdrop kitty" twice.

Is this possible already or a feature that could be added?

**Comment by noctuid** [comment]
I don't think it's possible to have the window never show up (at least I don't know of a way).  There will be some flicker, but you can immediately hide a program when it is started using a hook `tdrop --post-create-hook "unmap" kitty`.

**Comment by Schweber** [comment]
That works for me, thank you!
