### ISSUE TITLE
tdrop doesn't work with Wayland Window Manager

### ISSUE THREAD

**Issue by rabbitvictor** [noctuid/tdrop#404]
After updating Ubuntu to 22.04, tdrop kept throwing errors related do xprop and closing right after:
`xprop: error: invalid window id format: .`

tdrop command used: `tdrop kitty`

After some research, it turns out xprop does not work with Wayland at all. I just changed the window manager to Xorg and it works fine, but wanted to point out the issue in case there are some kind of workaround/development possible or others with the same problem.

**Comment by noctuid** [comment]
See #13 and #341.
