### ISSUE TITLE
AwesomeWM always trying to tile the dropdown

### ISSUE THREAD

**Issue by neondeex** [noctuid/tdrop#406]
When i try to run kitty or other program with 
tdrop -am -w50% -y 0 -x25% kitty
The programs appears fast in the master node and then is a dropdown but this makes me lose time and i don't like it
AwesomeWM

**Comment by noctuid** [comment]
This is a limitation of awesomewm.  As far as I know, it does not provide anything like oneshot/one time rules like bspwm and herbstluftwm have.  You will have to add a rule yourself to always float the dropdown (e.g. give it a custom title and use a rule that matches that title) if you want it to float immediately.
