### ISSUE TITLE
[Question] wezterm specify config and class

### ISSUE THREAD

**Issue by vihu** [noctuid/tdrop#419]
Hello, I tried searching through the issues but couldn't find the information I was looking for. I have the following sxhkd binding:

```
# wezterm quake style
super + Return
    tdrop -ma -w 100% -h 60% wezterm
```

I would like to specify a particular class and config when starting wezterm, for example:

```wezterm --config-file=/path/to/wezterm/quake.lua start --class wquake```

This way I can tell bspwm to always open wquake on a particular monitor.

So essentially, I wanted to ask how/if I can open wezterm with the above syntax using tdrop. Thanks!

**Comment by noctuid** [comment]
I just switched to wezterm and added a fix to handle wezterm with `--config-file` (#18), so you will need to update tdrop.

I don't think wezterm has a class option, so you will also need to change your command to `tdrop ... --class wquake wezterm --config-file=...`.

**Comment by vihu** [comment]
> I just switched to wezterm and added a fix to handle wezterm with `--config-file` (#418), so you will need to update tdrop.
> 
> I don't think wezterm has a class option, so you will also need to change your command to `tdrop ... --class wquake wezterm --config-file=...`.

Thank you, I will try the latest tdrop shortly. Wezterm does have a class option btw, however it's behind the `start` command, for reference: https://wezfurlong.org/wezterm/cli/start.html?h=class

**Comment by noctuid** [comment]
Okay, that command should just work on the latest tdrop then.  Let me know if it doesn't.
