### ISSUE TITLE
Artifacting on Xorg

### ISSUE THREAD

**Issue by twilbers** [noctuid/tdrop#42]
I am using Xorg with i3 as a window manager. When I execute tdrop it momentarily shift the background image (implemented with feh) and quick artifacting of current windows in new places on the screen (and sometimes even windows from other work spaces appears on screen). Then everything goes back to normal. I would use scratchpad but i really like tdrop for lanching ranger and the like.

I tried to use scrot to take a screen shot of the artifacting with a scrip that calls tdrop but this is the best i got (first is what it looks like after terminal is called):
![save](https://user-images.githubusercontent.com/1200207/39385208-9f8feede-4a3d-11e8-8041-c0548a0c68bb.png)
![save2](https://user-images.githubusercontent.com/1200207/39385209-9f9fc4e4-4a3d-11e8-9a6e-889d8667a94f.png)

```bash
xoffset=5
#xinterval=8
yoffset=30
width=1910
height=450
terminal=urxvt

#added to keep background from shifting
$HOME/.fehbg &&
tdrop -ma -x $xoffset -y $yoffset -w 1910 -h $height $terminal
scrot ~/save.png
```

**Comment by twilbers** [comment]
Here is a better pic of artifacting from a different workspace (4). Notice of the pdf file in zathura from workspace (3) shows and the background image is shifted: 
![save](https://user-images.githubusercontent.com/1200207/39385955-574d6f68-4a40-11e8-952c-d1ec177a5fe9.png)

**Comment by noctuid** [comment]
Yes, since i3 doesn't have the equivalent of bspwm's prefloat oneshot rules, tdrop cannot float the window immediately. Are you using a compositor? That may help somewhat. Alternatively/additionally, you can put a global rule to float the dropdown windows in your config:

```
for_window [title="tdropdown"] floating enable
```

And then add `--name "tdropdown"` to your tdrop command.

**Comment by twilbers** [comment]
Great thanks! I am using compton. Is there any rules that i should add to that?

**Comment by noctuid** [comment]
`fading = true;` may help make things smoother. Does adding that i3 rule fix anything?

**Comment by twilbers** [comment]
Yes this made a huge difference. Thanks for the support!

**Comment by noctuid** [comment]
Glad it helped.
