### ISSUE TITLE
Tdrop cause change workspace with BSPWM

### ISSUE THREAD

**Issue by lgtome** [noctuid/tdrop#421]
I using `bspwm` and I want to use tdrop as dropdown terminal, but if I invoke tdrop, I getting changed workspace.
Invoke command:

`tdrop -a -w 70% -h 35% -y 0 -x 15%  --class scratch alacritty --class=scratch`

**Comment by noctuid** [comment]
Is this the same issue as #369?  I could never reproduce.  Could you try to make the changes here and see if any of them fix the issue? https://github.com/noctuid/tdrop/issues/369#issuecomment-1492953253

**Comment by lgtome** [comment]
Yeah, it is a duplicate. Thanks!
