### ISSUE TITLE
Unable to toggle a tdrop terminal on the currently active and focused workspace (bspwm desktop)

### ISSUE THREAD

**Issue by tzeikob** [noctuid/tdrop#429]
I'm using the BSPWM as wm and my goal is to have a dropdown terminal always open at the currently active and focused workspace (aka dekstop for bspwm). The expected behavior is to have an sxhkd key binding and toggle on/off the dropdown terminal to show up on the current desktop no matter if it is empty of windows or not. Having the following configuration:

BSPWM
```shell
#!/bin/bash

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config normal_border_color "#AAAAAA"
bspc config active_border_color "#F0C674"
bspc config focused_border_color "#FF79C6"

bspc config external_rules_command "${HOME}/.config/bspwm/rules"
```

SXHKD
```shell
...
super + Return
  tdrop -am -w 80% -x 10% -y 50 cool-retro-term
...
```

Let's say I'm on the workspace 1 (empty of windows or not, doesn't matter) having the dropdown terminal open on that specific workspace doing some work and leave it open, If I move to the next workspace 2 and try to toggle on the dropdown via the same key binding the terminal shows up on that 2nd workspace, which is what is expected to be.

Things go a bit strange when after being at the workspace 1 doing some stuff with the dropdown terminal and then toggle it off, when I move to another workspace any try to toggle on the dropdown terminal back again the terminal shows up on the first workspace 1 and not of the 2nd one. I have tried to change the bspc setting `bspc config focus_follows_pointer` to `false` as I've seen this suggestion in other posts, but unfortunately this hasn't any effect.

I just want the dropdown terminal to open every time I toggle it on to the current active and focused workspace. What am I doing wrong?

Another strange behavior, that is not so deal breaker, is that on multiple monitor setups the dropdown terminal preferes to open of the currently active workspace over the currently focused. As where active and focused consider the bspwm terminology.

**Comment by noctuid** [comment]
The behavior you describe sounds like a bug that should be fixed already. Are you on the latest commit of tdrop?

> Another strange behavior, that is not so deal breaker, is that on multiple monitor setups the dropdown terminal preferes to open of the currently active workspace over the currently focused. As where active and focused consider the bspwm terminology.

It's been a long time since I've used bspwm, but doesn't "active" just mean focused on their desktop for windows or focused on their monitor for desktops?  There are multiple active desktops if you have multiple monitors, not one.  Could you elaborate on what behavior you're seeing and what behavior you want to see instead?

**Comment by tzeikob** [comment]
Oh dear, I just realized that the AUR version of the [tdrop](https://aur.archlinux.org/packages/tdrop) is outdated for a long long time stacked on 0.5 version. I have now cloned the master branch and via make install I can confirm that everything is working like a charm!

Sorry for wasting your time!

**Comment by noctuid** [comment]
My AUR package is tdrop-git.  Will add another tag soon, but I recommend sticking with  tdrop-git on Arch.
