### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by TeddyDD** [noctuid/tdrop#43]
HI. I'd like to package tdrop for [Void Linux](https://www.voidlinux.eu/)

To do that I need new release/tagged commit since last release was in 2015 (in general Void does not allow commit=version packages)

I'd be grateful for marking stable commit as release.

**Comment by noctuid** [comment]
There's a couple of things I want to do before tagging another release. Feel free to bump this in a week or so if I haven't done this.

**Comment by TeddyDD** [comment]
Bump :)

**Comment by noctuid** [comment]
Thanks for the reminder. I looked at my todo file, and nothing was important enough (or simple enough) to justify doing before a release. I went ahead and updated the documentation and tagged a new release. If/when you package tdrop for void, feel free to make a PR updating the Installation section or just let me know here, and I can do that.

**Comment by TeddyDD** [comment]
Hi, tdrop Void package has been merged so it should be avaliabe in the repo in few hours. It can be installed with `# xbps-install tdrop` :smiley:
