### ISSUE TITLE
Reopeining:  Shortcut opening new windows instead of focusing / hiding 

### ISSUE THREAD

**Issue by graven04** [noctuid/tdrop#431]
Reopening this issue: https://github.com/noctuid/tdrop/issues/350#issue-1157270572

I have the exact same problem but just installing dependencies does not fix the problem. I am running gnome wayland on arch. the command i use is the following:

 tdrop -ma -w -4 -y "$PANEL_HEIGHT"  kitty

**Comment by noctuid** [comment]
Have you read https://github.com/noctuid/tdrop?tab=readme-ov-file#wayland-support? You can take a look at the other wayland issues. You may be able to use tdrop on wayland, but tdrop does not support wayland

**Comment by graven04** [comment]
I did read the section and use the recommended methods but I didn't realise this was the expected behavior in Wayland. I had checked for an issue like this for wayland but hadn't spotted any so i though it might be something other than wayland. However, i switched to xorg and its works perfectly, and will probably just stick to xorg.
