### ISSUE TITLE
Problems with multiple monitors and -m

### ISSUE THREAD

**Issue by avanpo** [noctuid/tdrop#44]
I'm trying to use -m on i3 like so:

tdrop -m -a -w 1000 -h 800 -x 0 -y -840 -n ranger -f "-name floating -e ranger" urxvt

When I run this from a window on my laptop, it works. Ranger pops up bottom left. When I run this from a window on my external monitor (positioned to the right of my laptop), I get the following error:

```
/usr/bin/tdrop: line 237: 1080
1080: syntax error in expression (error token is "1080")
```

My xrandr output (with irrelevant parts omitted):

```
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.05*+  59.93  
... 
DP1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 530mm x 300mm
   1920x1080     60.00*+
...
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by avanpo** [comment]
Ah, I think I've found the problem.

https://github.com/noctuid/tdrop/blob/6adf44ef501f565a043306581ff9ea22fd434428/tdrop#L265

```
awk "/$current_monitor/ {gsub(\"primary \",\"\"); print \$3}")
```
Is matching both my monitors: the laptop screen, eDP1, and my external monitor: DP1. Then at line 237 bash freaks out because $total_height isn't a number or something. Not sure why it didn't have problems earlier.

Really, this is all my fault for not using HDMI.

**Comment by noctuid** [comment]
What's the output of this?
```
current_monitor=$(i3-msg -t get_workspaces | sed 's/{"num"/\n/g' | \
			awk -F ',' '/focused":true/ {sub(".*output",""); gsub("[:\"]",""); print $1}')
echo "$current_monitor"
```

Are you changing the name of your window manager with `wmname`?

**Comment by avanpo** [comment]
The output is DP1, and no.

I was able to fix the problem by adding a ^ character to the regex I mentioned above.

**Comment by noctuid** [comment]
Ah thanks. Sorry about the problem.

**Comment by avanpo** [comment]
No, thank you! tdrop is fantastic. And thanks for the lightning quick fix!
