### ISSUE TITLE
The command raises regular expression error for awk

### ISSUE THREAD

**Issue by yonekawa** [noctuid/tdrop#49]
`tdrop` command raises the following error when I executed.

```
awk: line 0: regular expression compile failed (missing operand)
x|+
awk: line 1: syntax error at or near )
```

I tried to fix syntax as following.

```
- #total_height=$(echo "$total_geo" | awk -F 'x|+' '{print $2}')
+ #total_height=$(echo "$total_geo" | awk -F '[x|+]' '{print $2}')
```

My env is
- dist: Ubuntu 18.04
- wm: GNOME shell
- shell: fish

**Comment by noctuid** [comment]
Right now only gawk is supported. I'll either explicitly use gawk or make the awk usage generic.

**Comment by noctuid** [comment]
It should work correctly with gawk installed now.
