### ISSUE TITLE
urxvt + "tabbed" plugin doesn't work with tdrop

### ISSUE THREAD

**Issue by ksoltysik** [noctuid/tdrop#54]
**How to reproduce:**
* Have `URxvt*perl-ext: tabbed` in your `~/.Xresources`.
* Invoke `pkill -f urxvt ; xrdb ~/.Xresources && tdrop -h 30% -f '--borderLess' -m -P 'wmctrl -i -r $wid -b add,above,skip_taskbar' urxvt`. Removing `-P` from here doesn't seem relevant in any way.

**Current result:**
`urxvt` appears in small window in the middle of screen. It's borderless, but no `wmctrl` options seem to be in effect. 

**Expected result:**
`urxvt` shows in on top area of the screen with no border. It doesn't show on taskbar and is stacked above other windows.

**Additional info:**
`tabbed` plugin is one of `urxvt` must-haves, especially along with dropdown terminal machinery. `tabbed` seem to be developed at https://github.com/gryf/tabbed. A code seems to have some hacks related to fake window resizing.

AUR version of tdrop (`tdrop-git`) updated 2016-03-23 16:11 was initially used but I reproduced it also with latest upstream commit.

**Comment by noctuid** [comment]
Do you get your expected result if you don't use the tabbed plugin or if you run the wmctrl yourself?

**Comment by ksoltysik** [comment]
Yeah I do.

**Comment by noctuid** [comment]
Does the wmctrl command work when tdrop is not being used and the tabbed plugin is being used? If not, then the issue is unrelated to tdrop.

**Comment by ksoltysik** [comment]
Removing my `wmctrl` part doesn't seem to be relevant: tdrop doesn't do tdrop things at all when `tabbed` is enabled. There's no `urxvt` dropdown then, just a centered window.

**Comment by noctuid** [comment]
It looks like tabbed is doing various weird things, like using urxvt's `-embed` flag to implement its functionality, that make it not work with tdrop. I'll look into this some more, but I'm not sure if it will be easily possible to get the correct window id on creation for the window the tabbed plugin is embedding urxvt into.

This doesn't solve your issue, but you could potentially use tmux, dtach, or whatever else as a workaround. Looking at tabbed's readme, I think tmux supports all of tabbed's functionality. There are also a lot of terminals like kitty that have builtin support for tabs

**Comment by noctuid** [comment]
Turns out it was pretty easy. Please try and let me know if everything is working as expected.

**Comment by ksoltysik** [comment]
It works like a charm:
![image](https://user-images.githubusercontent.com/47125363/52901542-3102c080-3205-11e9-8456-5fae927a00e1.png)

Thanks.
