### ISSUE TITLE
zsh icons don't appear on termite when used with tdrop

### ISSUE THREAD

**Issue by chahak13** [noctuid/tdrop#55]
I have been trying to set up tdrop for a couple of days now and am using `termite` as a terminal dropdown. I am also using Powerlevel 9k for zsh on the terminal. While using termite normally, there are no issues with the icons but when I open termite using tdrop, the icons seem to fail to load.

This is a screenshot of termite opened normally:
![Screenshot from 2019-04-09 17-52-11](https://user-images.githubusercontent.com/29800965/55800056-6d111e00-5af0-11e9-8b6a-c808bee9a8dd.png)

This is a screenshot of tdrop:

![Screenshot from 2019-04-09 17-53-09](https://user-images.githubusercontent.com/29800965/55800066-739f9580-5af0-11e9-8d63-ae1b1ebfdc6d.png)

Can you suggest why this is happening?

**Comment by noctuid** [comment]
I can't replicate this. Does this only happen for you with termite? Could you let me know your termite version and the tdrop command you are using?

**Comment by chahak13** [comment]
Hi, I am using termite v14 and am using the following command for tdrop:

`tdrop -m -a -w 40% -h 300 -x 30% -y 10 -s dropdown termite`

I don't have any other terminals so I'm not sure if it is happening only with termite or not.

**Comment by noctuid** [comment]
What window manager are you using? Please give me the output of the following command:

```sh
xprop -notype -id "$(xprop -root -notype | \
	awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" \
	-f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1

```

What are you using for `POWERLEVEL9K_MODE`?

Have you tried this without tdrop but still using tmux?

Also, if you could install and try with another terminal, that would be helpful.

**Comment by chahak13** [comment]
I'm using bspwm as my windows manager. It works with tmux on a normal terminal and not a dropdown. 

> What are you using for `POWERLEVEL9K_MODE`?

Could you slightly elaborate as to what you need?

> Also, if you could install and try with another terminal, that would be helpful.

Any terminals that you would suggest? It works for `gnome-terminal`

**Comment by noctuid** [comment]
> Could you slightly elaborate as to what you need?

That environment variable controls the font used. If unset it just uses the powerline fonts by default. Which powerline font have you set as the font in your termite config.

>Any terminals that you would suggest? It works for gnome-terminal

That's fine then. Just let me know the font and I'll try again with that font.

**Comment by chahak13** [comment]
> That environment variable controls the font used. If unset it just uses the powerline fonts by default. Which powerline font have you set as the font in your termite config?

Ah right. Sorry, did not realise you were talking about the environment variable. I'm using nerdfont.

` POWERLEVEL9K_MODE="nerdfont-complete"`

**Comment by noctuid** [comment]
Could you give me the line from your termite config for setting the font as well?

**Comment by chahak13** [comment]
I am so sorry. I sent the wrong font and forgot that I had changed the font. I am actually using `hack 10`.

This is the line from my `.zshrc`:

`POWERLEVEL9K_MODE="hack 10"`

and this is the line my termite config:

```
[options]
scroll_on_output = false
scroll_on_keystroke = true
audible_bell = false
mouse_autohide = true
allow_bold = true
dynamic_title = true
urgent_on_bell = true
clickable_url = true
cursor_blink = on
font = hack 10

[colors]
background = rgba(63, 63, 63, 0.5)
foreground = #ebdbb2
color0  = #282828
color8  = #a8a29c
color1  = #cc241d
color9  = #fb4934
color2  = #3ab733
color10 = #b8bb26
color3  = #bfbfbb
color11 = #ebf435
color4  = #21cad3
color12 = #83a598
color5  = #b16286
color13 = #d3869b
color6  = #689d6a
color14 = #8ec07c
color7  = #eaeaea
color15 = #ebdbb2
```

**Comment by noctuid** [comment]
My understanding from reading the documentation for powerlevel9k is that `POWERLEVEL9K_MODE` should be `nerdfont-complete` and the font in the termite config should be something like `Hack Nerd Font Mono 10` or maybe `Hack Regular Nerd Font Complete` not just `hack`. That said, even with your configuration I can't replicate the issue. I don't really have any idea how tdrop would cause this issue. It may not help, but try updating your font line in the termite config. If that doesn't fix it, there may not be much else I can do.

**Comment by chahak13** [comment]
I tried the suggested changes but it still doesn't work. I will take a deeper look into my configs as I think that is the only place something is probably going wrong. Thanks for the help though!

**Comment by noctuid** [comment]
The only easy thing I could suggest would be to see if using a `bspc` oneshot rule to float the next termite window causes this issue or if resizing with xdotool causes it. You could try running this in a terminal to see if it causes the issue:

```sh
xdotool getactivewindow windowmap windowmove "30%" 10 windowsize "40%" 300
```

You could also try removing `-m`. In any case, there's probably not anything I can do in tdrop to fix this.

**Comment by noctuid** [comment]
Since termite is dead, I will no longer actively support it.
