### ISSUE TITLE
Konsole throws out error

### ISSUE THREAD

**Issue by Vistaus** [noctuid/tdrop#58]
When I bind Konsole and open it using the bound shortcut, it throws out this error and can't be used:

`Konsole is unable to open a PTY (pseudo teletype). It is likely that this is due to an incorrect configuration of the PTY devices. Konsole needs to have read/write access to the PTY devices.`

How do I fix that? Opening Konsole directly (i.e. without tdrop) works fine.

**Comment by noctuid** [comment]
I can't replicate this. Can you give me more information? What distro are you on? What is the exact command you are using (e.g. `tdrop konsole` and `tdrop -am -s foo` work for me). What window manager/desktop environment are you using? How are you binding the key?

**Comment by Vistaus** [comment]
Sorry, I should've added more information in the first place!

OS: Arch Linux
DE: Trinity Desktop Environment (TDE)
Window Manager: TWin

I used the command from the example in the readme, with 'termite' replaced by 'konsole': tdrop -ma -w -4 -y "$PANEL_HEIGHT" -s dropdown konsole

**Comment by noctuid** [comment]
I'll install trinity and try to replicate. Feel free to ping me in a week or two in case I forget.

Are you using the regular `konsole` package or one from the aur? Does this happen if you just run the tdrop command in a terminal, and if not, how are you binding the key?

**Comment by Vistaus** [comment]
Thanks for looking into it! :)

I'm using the regular konsole package from the Trinity repo: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#trinity

**Comment by Vistaus** [comment]
*ping* :smile_cat:

**Comment by noctuid** [comment]
Does `tdrop konsole` work for you? I've installed trinity and can confirm `-s` at least does not work. Do you also get messages such about `_NET_ACTIVE_WINDOW`, `_NET_CURRENT_DESKTOP`, and `_NET_DESKTOP_WM` not being supported? I will have to mess around more with Trinity; it is pretty broken for me at the moment.

**Comment by Vistaus** [comment]
Yes, tdrop konsole works fine :) I don't get any of your other messages.

**Comment by noctuid** [comment]
Okay, I was able to get Trinity working correctly. Unfortunately, I can't reproduce any of these problems. Does this only happen for konsole? For me, there is no konsole in the trinity repos; I have konsole from `extra` installed. Do you have this or something different?

**Comment by Vistaus** [comment]
I'm using Konsole from the unofficial Trinity repo.

**Comment by Vistaus** [comment]
It seems like Konsole doesn't like quotes ("xyz") attached to it. tdrop seems to pass a command in quotes to open Konsole, something with bash -c. Going to play around with that.

**Comment by Vistaus** [comment]
Yep, that works! Changed line 620 in /usr/bin/tdrop to

```
else
			program_command="$program_command"
```

and now Konsole works fine :)

**Comment by noctuid** [comment]
Sorry about that. I thought you were saying there was actually a `trinity/konsole` package, but konsole is just a package included in `/opt/trinity/bin`. The default konsole works with either quotes or no quotes. I removed the quotes so both work. Let me know if you have any issues.

**Comment by Vistaus** [comment]
No problem! And thanks for including the fix! :)
