### ISSUE TITLE
X Error of failed request:  BadWindow (invalid Window parameter)

### ISSUE THREAD

**Issue by slarsar** [noctuid/tdrop#59]
I want to use hot key to invoke emacs, so I set short key for emacs: `trop emacs`, but then emacs start in gui window with console mode.

emacs only start console mode in terminal  when `emacs -nw`
```bash
➜ tdrop emacs                

(emacs:3390940): Gtk-WARNING **: 19:08:36.408: Theme parsing error: gtk.css:123:146: Expected a valid selector

(emacs:3390940): Gtk-WARNING **: 19:08:36.415: Theme parsing error: gtk.css:9319:2: '/*' in comment block

(emacs:3390940): Gtk-WARNING **: 19:08:36.415: Theme parsing error: gtk.css:9320:20: Expected semicolon

(emacs:3390940): Gtk-WARNING **: 19:08:36.418: Theme parsing error: gtk.css:13298:18: Invalid name of pseudo-class
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0xb92d1e
  Serial number of failed request:  1356
  Current serial number in output stream:  1356


```

emacs should start as :
![image](https://user-images.githubusercontent.com/46400566/69234325-d51cfc00-0bc9-11ea-94d8-be3224521ba4.png)

but `tdrop emacs` cause this:
![image](https://user-images.githubusercontent.com/46400566/69293592-51ecbc00-0c44-11ea-8cf6-9069b2361805.png)

![image](https://user-images.githubusercontent.com/46400566/69234635-9b002a00-0bca-11ea-8aae-2e1870017c88.png)

**Comment by noctuid** [comment]
I don't fully understand the issue. Are you trying to start a GUI Emacs frame? And what is the behavior you are actually seeing? Is there something wrong in the last screenshot?

**Comment by slarsar** [comment]
@noctuid  hello, I am trying to launch a GUI Emacs from `tdrop emacs` , but `tdrop emacs` launch emacs on terminal mode.

GUI emacs will show an Emacs Logo on startup, but Terminal emacs won't.

you can launch GUI emacs by `$ emacs` and launch terminal emacs by `emacs -nw`

**Comment by noctuid** [comment]
I can't replicate this and don't see how it would be possible. I get the logo if I run `tdrop -f '-q' emacs`, for example. Are you saying it's actually running Emacs in a terminal or just that the logo isn't there? If you run `xprop` in a separate terminal and then click on the Emacs started by `tdrop emacs`, what is the output?

**Comment by slarsar** [comment]
@noctuid thank you.
