### ISSUE TITLE
Passing arguments to programs

### ISSUE THREAD

**Issue by 97-109-107** [noctuid/tdrop#6]
In order to eliminate flickering on an i3wm setup as well as having the tdrop window 'follow' the user across workspaces one would need to be able to label the terminal with a class or title.

For example, for urxvt I'd like to pass a specific title to it (using `` -title "tdrop"``) to be able to specify particular rules to it. 

I think I'm missing something because the following fails on me:
``tdrop -a -h 33% -y 18 -m -s desktop -n dropdown 'urxvt -title "this"'``

Am I missing something obvious or is this not possible in the current state?

**Comment by noctuid** [comment]
I think I had an option like this at one point (maybe before creating this repo) and removed it because it wasn't working properly. I'd rather use a dedicated flag for this, so you can use `-f` or `--program-flags`. For example: `tdrop -a -h 33% -y 18 -m -s desktop -n dropdown -f "-title this" urxvt`.

**Comment by 97-109-107** [comment]
Thanks, works.

The rules relevant to the usage of tdrop are twofold. The first one is for tdrop to 'follow' me through workspaces 
````
bindsym $mod+1 workspace 1: www; [title="dropdown"] move workspace current;
bindsym $mod+2 workspace 2: vim; [title="dropdown"] move workspace current;
````
This is necessary because there is no concept of an omnipresent window in i3wm.

As I don't use a compositor, the second rule is for minimizing the flickering:
````
for_window [title="dropdown"] floating enable
````
