### ISSUE TITLE
Close opened drop

### ISSUE THREAD

**Issue by sa5gap** [noctuid/tdrop#60]
How to close any opened dropdown windows?

**Comment by indeedwatson** [comment]
What WM or DE are you using? I believe that's beyond the role of tdrop.

**Comment by noctuid** [comment]
Do you mean hide or actually close the window? If you want to close it, then @indeedwatson is right, tdrop doesn't do that.

**Comment by sa5gap** [comment]
> What WM or DE are you using? I believe that's beyond the role of tdrop.

i3wm

**Comment by sa5gap** [comment]
> Do you mean hide or actually close the window? If you want to close it, then @indeedwatson is right, tdrop doesn't do that.

I would like to hide any dropdown window by use single keybinding.
here is part of my config (i3):

`bindsym Print exec --no-startup-id tdrop -ma -s desktop -y 16 urxvt -name dropdown`
`bindsym Shift+Print exec --no-startup-id tdrop -ma -s desktop -y834 -w1338 -h366 -x291 -n2 urxvt -name dropdown -bg rgba:0000/0000/0000/AAAA`
`for_window [instance="dropdown"] floating enable border none`
`for_window [instance="dropdown2"] floating enable border none`

i.e. what it might look like in config:
`bindsym $mod+Esc tdrop --hide-all`

**Comment by noctuid** [comment]
Just to confirm, you want a keybinding to hide all dropdown windows?

**Comment by sa5gap** [comment]
> Just to confirm, you want a keybinding to hide all dropdown windows?

yes exactly

**Comment by noctuid** [comment]
Okay, try `tdrop hide_all` with the latest version.

**Comment by sa5gap** [comment]
> Okay, try `tdrop hide_all` with the latest version.

perfectly! thanks a lot!
