### ISSUE TITLE
Sometimes different binds will utilize the same window

### ISSUE THREAD

**Issue by indeedwatson** [noctuid/tdrop#63]
I can't figure out what this happens. Here's my binds:

```
# dropdown
super + i
    tdrop -ma -n dropdown -w 44% -h 53% -y 24% -x 27% termite

# todo
super + u
    tdrop -ma -n todo -f '-e "nvim /home/yama/vimwiki/todo.txt"' \
        -w 48% -h 53% -y 27% -x 1% termite

# discord
super + Return; {d, @d}
    {tdrop -m -n cordless -f '-e cordless' termite, \
    pkill -ALRM sxhkd

```

Usually everything works as expected. But sometimes (like right now) I'll press any of those binds and it will call the same window, whichever I opened first.

So if I press `super + Return; d` first, press it again to hide, and then press `super + i` it will bring up the cordless window, floating.

**Comment by noctuid** [comment]
That's pretty bizarre. How often does this happen? Has it happened with other terminals?

Not related (probably), but you can now just put the program flags after the program name. `-f` only exists for backwards compatibility and shouldn't be used.

**Comment by indeedwatson** [comment]
Haven't tried other terminals. It seems to happen pretty randomly and frequently enough that I notice it.

>  you can now just put the program flags after the program name. -f only exists for backwards compatibility and shouldn't be used.

 ```> ~ tdrop "termite -e nvim"
The program should be in PATH and not contain flags.

 ✗ ~ tdrop termite "-e nvim"
Exactly 1 positional argument is required. For help use -h or --help or see the manpage.

 ✗ ~ tdrop termite -e nvim  
Exactly 1 positional argument is required. For help use -h or --help or see the manpage.```

**Comment by noctuid** [comment]
The last form is right. I think you're on an older version.

**Comment by Foldex** [comment]
Can confirm this behavior on f4f0f34, using urxvt and bspwm.
```
tdrop -ma -w 50% -h 35% -y 20 -x 450 -n 1 urxvt -e weechat
tdrop -ma -w 50% -h 35% -y 20 -x 450 -n 2 urxvt -e sysupg
```

I've tried using `-n` as well as `--class` in combination with `urxvt -name`, but very rarely one keybind will bring up the wrong window. Checking `/tmp/tdrop_user/urxvtX` confirms the stored window ids become the same.

**Comment by noctuid** [comment]
To confirm, they start out different and then change?

**Comment by Foldex** [comment]
Yep, though it is pretty infrequent; It took me a good bit of spamming the keybinds to get this example. Out of four terms with different `-n`  and `--class` designations they all wound up eventually sharing the same window id.

```
$ ls
urxvt1  urxvt2  urxvt3  urxvt4
```

```
$ cat urxvt*
58720266
58720266
58720266
58720266
```

It isn't strictly limited to tdrop spawned terms though, as I have had it randomly grab normally tiled ranger terms as well.

**Comment by indeedwatson** [comment]
It's not limited to terminals either, just had it happen with firefox. No idea what's going on, I think it started happening in one of the recent updates. I might downgrade and see if the behavior stops.

**Comment by noctuid** [comment]
The only way this could happen as far as I can tell is if tdrop checks whether the window id exists and it no longer does according to xdotool or xprop. And even then, I don't see how it could happen for different programs. @indeedwatson Do you mean that you have firefox dropdowns or that a dropdown keybinding for another program started toggling firefox? Unfortunately, no amount of spamming one or two keybindings manually or with an extremely high repeat rate results in this for me.

If I can't replicate this, I can maybe create a debug branch to get some extra info from one of you.

**Comment by indeedwatson** [comment]
> Do you mean that you have firefox dropdowns or that a dropdown keybinding for another program started toggling firefox? 

The latter.

**Comment by noctuid** [comment]
I can definitely replicate this after updating (bspwm and everything). Will look into.

**Comment by clicseo** [comment]
Hello, also having this problem. Happens with pcmanfm and firefox. 
Using "tdrop -a pcmanfm" as shortcut. If a pcmanfm tdrop instance already exists and its just toggling, everything works. 
But if you just have a firefox instance opened and execute the shortcut once, I get the firefox window disappear and be the one that starts toggling instead of pcmanfm.

**Comment by noctuid** [comment]
I can't replicate. What window manager/desktop environment are you using?

**Comment by Unearthlybrutal** [comment]
Similar problem here with alacritty. When there's alacritty windows open and I open alacritty with "tdrop -ma -w 50% -y 30% -x 27% alacritty -t "scratchpad"", sometimes tdrop "hijacks" one of the alacritty sessions.

**Comment by noctuid** [comment]
Okay, so I found a consistent way to replicate which makes the issue obvious. Kitty is just an example here.

1. Open kitty 1 dropdown
2. Open kitty 2 dropdown
3. Close kitty 2 dropdown
4. Close kitty 1 dropdown
5. Open kitty 2 dropdown
6. Open kitty 1 dropdown - should close kitty 2 instead of opening kitty 1
7. Repeat if it didn't happen

The important part is to open a different dropdown from one that was just closed. The wid no longer exists for the closed dropdown, but it is still stored for it. If the new dropdown gets that wid, then this issue will happen.

I can no longer replicate using the changes in the PR I just opened. If anyone is interested, please try it out.

**Comment by noctuid** [comment]
Merged. Please let me know if you still have issues.

**Comment by noctuid** [comment]
There's still an issue for non-tdrop managed windows. E.g.

1. Close tdrop kitty
2. Open non-tdrop kitty
3. Open tdrop kitty

I need to figure out some way to tell when this has happened.

**Comment by noctuid** [comment]
Okay, there should be no more cases where this is happening.
