### ISSUE TITLE
JWM support

### ISSUE THREAD

**Issue by int-72h** [noctuid/tdrop#64]
In JWM, there appears to be a small gap on my system at the top, which is about two pixels with Alacritty. Using Tilix's quake functionality, it appears to work fine. Running ``xdotool search --class alacritty windowmove 0 0`` after start appears to work, but it won't work with the -P hook.
The command I tried in ``.jwmrc``:

```<Key key="F8">exec:tdrop -P xdotool search --class alacritty windowmove 0 0 -ma -w 100% -h 424 alacritty</Key>```

An alternative here would be just using Awesomewm, and I am considering it, but it'd be nice for tdrop to support everything.

**Comment by int-72h** [comment]
Note: using sxhkd results in an X error on start, but no gap on the first open. The gap however persists when closed and reopened.

**Comment by noctuid** [comment]
The default y offset is 2 (see the man page for information on why). You can try `-y 0` and see if that works well for you. Also, you need to have quotes around a `-P` command (not sure if you did or not).
