### ISSUE TITLE
tdrop moving kitty terminals from other workspaces bspwm

### ISSUE THREAD

**Issue by PaxSov** [noctuid/tdrop#67]
When I use this program it calls my openvpn terminal form another workspace. This always happens with kitty terminal. This does not happen if openvpn is running with another terminal emulator. This only happens if tdrop and openvpn is kitty.
This does not happen with any other terminal process.
I do not know what is causing this strange bug

**Comment by noctuid** [comment]
I think this should be fixed as of today. If it still happens, please post the full tdrop commands. Is the openvpn terminal a dropdown?
