### ISSUE TITLE
tdrop doesn't respect bspwm pseudo-tiled window sizes

### ISSUE THREAD

**Issue by jameh** [noctuid/tdrop#69]
When I make a tdrop window with a window in the pseudo-tiled state which is smaller than the tiled state, tdrop resizes it to the size of a regular tiled window.

## Reproduction steps

Create a new dropdown, put it into `pseudo_tiled` state, and resize it smaller than regular tiled windows. e.g.

```
tdrop alacritty
```

Then in the dropdown

```
bspc node -t pseudo_tiled
```

and resize it. Then toggle the dropdown to disappear and reappear. It should appear as a full-sized tiled window.

I have tried also adding a pre-map rule to force the state to "pseudo_tiled", but that doesn't work either:

```
tdrop -p 'bspc rule -a alacritty state=pseudo_tiled' alacritty
```

**Comment by noctuid** [comment]
Currently tdrop always enforces specified geometry (this is necessary when opening a dropdown on a monitor with a different size from the last, for example). I could add a flag to only set the geometry on creation or to never set the geometry. Would that be sufficient?

**Comment by jameh** [comment]
Possibly. 

Shouldn't the window manager generally take care of geometry? 

Which specified geometry is tdrop enforcing in my example?

**Comment by noctuid** [comment]
> Shouldn't the window manager generally take care of geometry?

The current assumption is either that you are using a floating dropdown (which is more common) or you are using a tiled dropdown and the xdotol commands for changing the geometry should have no effect. That's why there's no way currently to not specify a width, height, x, and y. I could add it as an option if necessary.

> Which specified geometry is tdrop enforcing in my example?

It doesn't actually work for tiled windows, but `xdotool windowsize` is causing this issue. I don't know whether it's expected for psuedo-tiled windows to respond to windowsize, but they definitely don't size correctly. This is potentially something that could be fixed in bspwm, but I'm not sure.

**Comment by jameh** [comment]
Ah ok, yeah `xdotool windowsize` resizes pseudo_tiled windows the same as tiled windows with respect to percentages.

Personally, I was a bit surprised that tdrop enforces width and height when I left them unspecified - I expected default behaviour to be to leave the geometry that the window manager and application would otherwise assign, but allow to enforce a size with tdrop's `-w` and `-h` flags.

Having a flag to disable tdrop's setting of geometry should do the trick though if you don't think that should be default.

**Comment by noctuid** [comment]
> Having a flag to disable tdrop's setting of geometry should do the trick though if you don't agree that it should be default.

Probably it would be less surprising to not do any geometry alterations by default, but I think the current defaults are more convenient. The default size for many terminals is way too small. I'd also rather not make a breaking change to the defaults. I've added a branch `feature/#69-no-alter-geometry` where you can specify `-w "" -h "" -x "" -y ""` to prevent any geometry setting. Let me know if this works and is a good enough solution for you.

**Comment by noctuid** [comment]
Closing, as it is now possible to have tdrop not manage the geometry on master.
