### ISSUE TITLE
Remember last window position/Bring window to front functionality

### ISSUE THREAD

**Issue by mliudev** [noctuid/tdrop#70]
Is there a way to have tdrop open the window in the last closed position? In addition is there a way to focus the window if it's already open?

**Comment by noctuid** [comment]
> Is there a way to have tdrop open the window in the last closed position?

Do you mean with the same x/y offset or something else? Tdrop currently always enforces the specified x and y offsets. For some window managers it could be possible to keep the old position, but others move the window after it is shown.

> In addition is there a way to focus the window if it's already open?

Not currently, but I could add a command to do this if you want.

**Comment by mliudev** [comment]
@noctuid Yes, that would fit my workflow better. I don't necessarily want a drop down so much as a hotkey to open the terminal in the last remembered position if it's not open and focus to it if it is. As a bonus the hotkey would also move it to the workspace I'm currently in if it's already open or open it if it isn't.

This is similar to the behavior of iterm2 hotkey windows.

**Comment by fenuks** [comment]
Yakuake also has similar behaviour. If windows is visible, but is not focused, it simply gains focus on the hotkey press, and it can be configured to retract to same monitor it previously used, regardless of the mouse pointer. Personally I find such configuration more convenient to use, and if I want terminal window on other screen, I can explicitly move it. It would be great if tdrop allowed to replicate this behaviour.

**Comment by goncalvesnelson** [comment]
I would also really like this feature. Just like @mliudev, I think it would be great if we could mimic the behavior of iTerm2.

**Comment by noctuid** [comment]
I've added the `-A` flag to always prefer activating/showing the dropdown. You can have tdrop not manage positioning with `-x "" -y ""`. There is not currently support for only having tdrop manage the initial positioning, but I could add that too if there is interest.

**Comment by Freed-Wu** [comment]
thanks for `-A`.
Now if foobar is not visual , `tdrop -A foobar` will make foobar visual but not focused, `tdrop -A foobar` again will make foobar focused.
However, how can we press one command make foobar visual and focused? if it can be done, we can use one hotkey to toggle foobar, just like guake or other drop-down terminal.

**Comment by mliudev** [comment]
@noctuid Thanks for getting around to this. My workflow has since changed to using i3 instead so I don't use this solution anymore. Feel free to close this and thanks for this cool utility.

**Comment by eval-exec** [comment]
Thank you.
Can tdrop remember last opened window position and size now ?

**Comment by noctuid** [comment]
> Now if foobar is not visual , tdrop -A foobar will make foobar visual but not focused, tdrop -A foobar again will make foobar focused.

I can't replicate this. Can you elaborate on what is happening? If foobar is hidden and you press the hotkey, it is shown but not focused? What window manager are you using?

>  Can tdrop remember last opened window position and window size now?

What behavior do you want? e.g.:
- option to only manage initial position and sizing
- option to store the current geometry when hiding and then restore when opening

The second may not be necessary on your window manager. You can see if the geometry is maintained if you specify the geometry options as empty, e.g `-x "" -y ""...`

**Comment by allemangD** [comment]
> Can tdrop remember last opened window position and window size now?

I'm interested in this also. Gnome 3 and `-x '' -y ''` don't play nice; the window always opens in the top-left corner; even if the window is already open and brought to front with `-A`. For reference I'm using `tdrop -maA -x '' -y '' -h '' -w '' kitty`. The window appears in the top-left regardless of context.

There is also a strange case with `-A`; if the window is hidden then the shortcut brings the window to the front and focuses it. Pressing the shortcut a second time does nothing, even though it should hide the window (since it's focused). Pressing the shortcut a _third_ time does hide window.

I would expect pressing the shortcut once to bring the window to front, and once more to hide the window.

**Comment by noctuid** [comment]
@eval-exec @allemangD I've added a `--remember` flag to remember/restore the geometry in the `feature/remember` branch if you want to test it. It does not yet support integration with `-m`.

**Comment by allemangD** [comment]
@noctuid feature/remember is working for me on mutter, as long as `subtract_when_same` is false. So the command I'm using is this, which works great on one monitor. This workstation doesn't have multiple monitors, but I can test on a multi-monitor setup when I get home if that would help.

    tdrop -aAS --remember -w '' -h '' -x '' -y '' kitty --class=kitty-tdrop

Some alias for `-w '' -h '' -x '' -y ''` might be helpful, since it's just asking to defer placement of new windows to the WM... maybe `-d/--defer`?

**Comment by noctuid** [comment]
It won't currently work on a multi-monitor setup. I will have to add logic to subtract from/add to x/y positions based on the curernt monitor.

> Some alias for -w '' -h '' -x '' -y '' might be helpful, since it's just asking to defer placement of new windows to the WM... maybe -d/--defer?

That seems reasonable. Maybe `--unmanage` or `--no-manage`. `-d` is already taken, so I will try to think of a good letter.

**Comment by eval-exec** [comment]
> @eval-exec @allemangD I've added a `--remember` flag to remember/restore the geometry in the `feature/remember` branch if you want to test it. It does not yet support integration with `-m`.

Thank you, I tested `feature/remember` branch, it work as expect. :-D

**Comment by eval-exec** [comment]
> I've added -N / --no-manage as shorthand. --remember now works with --monitor-aware / -m. Let me know if there are any issues.

thank you  :-)
