### ISSUE TITLE
toggle feature not working on opensuse tumbleweed

### ISSUE THREAD

**Issue by mglevy** [noctuid/tdrop#71]
Hello!

when I keybind an action (either my note taking application cherrytree or xterm) it opens a new window instead of toggling back to an open one. How do I go about figuring out what is wrong?

tdrop -a xterm
tdrop -n 1 xterm
tdrop xterm
tdrop -n1 xterm

all lead to a new window opening

Thank you,

Michael Levy

**Comment by noctuid** [comment]
Can you do the following?

- try with a few more programs and see if it works for any of them
- see if a `/tmp/tdrop_<username>/xterm` file is created with a window id after running `tdrop xterm`; what is the id in the file and what is the result of running `xdotool getactivewindow` in the created xterm?
- post the output of the following command `xprop -notype -id "$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" -f _NET_WM_NAME 8u | awk -F "\"" '/WM_NAME/ {print $2}' | head -n 1`

**Comment by mglevy** [comment]
1. tdrop libreoffice and tdrop krita will open only one window and not toggle off
    cherrytree, notepad, vlc, and xterm open a new window each time i push the hotkey (F10, if that matters)
2.  /tmp/tdrop_<username>/ has the following contents
auto_hidden  cherrytree  cherrytree1  krita  libreoffice  log  notepad  tdrop  vlc  xterm  xterm1
where every file is empty and auto_hidden has a blank class and wid file
and a geometry file with contents:

xoff=0
yoff=0
width=
height=

3.  in the xterm after calling tdrop xterm and then calling xdotool getactive window I get a seemingly random different number each time i push my hotkey

142606370
144703522
153092130
148897826

             etc
I also needed to install xdotool if that is pertinant information

4.  the command suggested yields xfwm4 in both the hotkey created xterm and tilex

Thank you!

**Comment by noctuid** [comment]
> I also needed to install xdotool if that is pertinant information

Xdotool is a required dependency. Do you have [all dependencies](https://github.com/noctuid/tdrop#requirements) installed (including xwininfo)? If so, I just added a `--debug` flag. If you could download the latest tdrop, run `tdrop --debug xterm`, and provide the contents of `/tmp/tdrop_<user>/log`, that would be helpful.

**Comment by mglevy** [comment]
I got used to my package manager installing everything for me! Thank you for holding my hand through reading those dependencies. Sorry for wasting your time. Thank you for a very positive first time posting on a programming form. Have a nice day!
