### ISSUE TITLE
Is it possible to have the terminal window follow virtual desktop switching?

### ISSUE THREAD

**Issue by JanFisherGG** [noctuid/tdrop#75]
I'm using KDE Konsole with tdrop. I've used Tilix in the past and it travels with you whenever you change a virtual desktop, Konsole using tdrop stays in the same virtual desktop. Moreover, hiding and bringing it up with tdrop doesn't bring up Konsole in the new virtual desktop. Is it possible to achieve Tilix like behavior with tdrop?

**Comment by noctuid** [comment]
The current behavior depends on the window manager. If you want the window sticky, you can try using `wmctrl` (untested but something like `tdrop --post-create-hook 'wmctrl -r $wid -b add,sticky' ...`.

**Comment by garret** [comment]
What about bspwm? If I append `-post-create-hook 'wmctrl -r $wid -b add,sticky' ...` I can still see that the dropdown application does not stay sticky/is still present when I change workspace.

**Comment by noctuid** [comment]
Bspwm has it's on sticky capabilities. You can try using the command `bspc node -g sticky` or something similar instead.

**Comment by garret** [comment]
@noctuid Giving [bspc node -g sticky](url) works inside an alacritty terminal instance but I cannot understand which command I should give with `tdrop`. I get the following error when trying with this command: 
```
garret@void ~> tdrop -mat -h 25% -w 98% -x 15 -y 30 alacritty -post-create-hook 'bspc node -g sticky'
Exactly 1 positional argument is required. For help use -h or --help or see the manpage.
garret@void ~ [1]>
```
