### ISSUE TITLE
tdrop - multi-monitor - always open on the same monitor

### ISSUE THREAD

**Issue by zwessels** [noctuid/tdrop#76]
is it possible to have tdrop always open the same monitor in a multi-monitor setup regardless of where the mouse is, which window/monitor has focus, etc.? 

wm: kwin

**Comment by noctuid** [comment]
If you know the monitor name, and it won't change, I could add a flag to specify the monitor to open the window on.

**Comment by noctuid** [comment]
I added a `--monitor` flag for this (e.g. `--monitor HDMI-0`). This will only work if you are using a floating dropdown (and `-m`).
