### ISSUE TITLE
Can't start a tmux session with termite

### ISSUE THREAD

**Issue by loki7990** [noctuid/tdrop#79]
Hello,

When I try to start a dropdown terminal using termite with the following command: `tdrop -m -w 70% -h 60% -x 15% -y 46 -s Dropdown termite --name dropdown` I get the following error message:
```
the command failed to run: Failed to execute child process “bash -c tmux attach-session -dt Dropdown 2> /dev/null || 			tmuxifier load-session Dropdown 2> /dev/null || 			tmuxinator start Dropdown 2> /dev/null || 			tmux new-session -s Dropdown” (No such file or directory)
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x4400001
  Serial number of failed request:  166
  Current serial number in output stream:  166
Error: Exceeded timeout of 10 seconds waiting for program.
```
If a tmux session with the Dropdown name has already started, then the above command works fine. It seems it can't create a new tmux session for some reason.

**Comment by noctuid** [comment]
Please try now.

**Comment by loki7990** [comment]
It works, except if I provide a name through the -s switch the tmux session
doesn't get that name. It's just 0. Thanks for looking into this so quickly!

**Comment by Barbarossa93** [comment]
I figured out the problem. You have: `program_command+=(-e "bash -c $tmux_command")`; Changing it to `program_command+=(-e "bash -c '$tmux_command'")` worked correctly.

**Comment by noctuid** [comment]
Sorry, will push a fix in a minute.
