### ISSUE TITLE
Argument parsing accepts wrong usage in special cases

### ISSUE THREAD

**Issue by schoettl** [noctuid/tdrop#8]
I noticed a little bug that I made a little bit worse with my last patch to be honest.

When a user calls tdrop in a wrong way it's behavor can be unpredictable. Example: `tdrop --width termite` ( -> long option that requires an argument and no argument is given)

In this case the problem with the current code is that `$OPTARG == $OPTION`. So the default value for `width` will be overridden by the value `"width"`. It would be better to have an error message.

To don't override the default value for `width` with this non-sense string, the patch below can be applied.

But there is still a problem when the default value for `width` is not the empty string, but e.g. a number.

I don't know... we can also keep the code as is and so the user just has to use the program in the correct way.

----

```patch
diff --git a/tdrop b/tdrop
index 4827d68..44964ed 100755
--- a/tdrop
+++ b/tdrop
@@ -91,8 +91,16 @@ do
 	a) auto_detect_wm=true;;
 	m) monitor_aware=true;;
 	-)
-		OPTION=${OPTARG%%=*}
-		OPTARG=${OPTARG#*=}
+		if [[ $OPTARG == *=* ]]; then
+			# long-option with argument
+			OPTION=${OPTARG%%=*}
+			OPTARG=${OPTARG#*=}
+		else
+			# long-option without argument
+			# set OPTARG to "", though it's still invalid for numbers
+			OPTION=$OPTARG
+			OPTARG=""
+		fi
 		case $OPTION in
 		height) height=$OPTARG;;
 		width) width=$OPTARG;;
```

**Comment by noctuid** [comment]
Ideally the user won't make any mistakes, but I added some basic option validation in 335075297 to prevent some more likely mistakes (like the ones you give). I'm not going to add checks for everything (e.g. to prevent useless options that wouldn't do anything in a specific case like `-f` with `--clear`), but if you think of another case that is broken or causes something unexpected, let me know.

**Comment by schoettl** [comment]
Thanks, nice work!

BTW, I recently learned a different way to handle long-options in Bash scripts. Maybe you know that already:

http://www.kfirlavi.com/blog/2012/11/14/defensive-bash-programming/
-> Command line arguments

It seems to be a pretty reliable and defensive approach.

**Comment by noctuid** [comment]
I stumbled across that article a while ago. I don't like some of suggestions, but I might as well implement some of them (like making certain variables readonly). As for the approach for using long options, it may be easier to add support for "--long-opt value" syntax that way. I'll look into it. Thanks for posting.

**Comment by noctuid** [comment]
@schoettl I did something similar in 8748745 with sed. It seems to work fine with everything I tested, so I may merge it after trying it out some more.
