### ISSUE TITLE
Using with tabbed and alacritty

### ISSUE THREAD

**Issue by farzadmf** [noctuid/tdrop#80]
Hi, first of all, thank you for the great tool, it's my go-to for my dropdown terminal.

Currently, I'm using `alacritty` as my terminal, and as you probably know, it doesn't have tab support (and the author(s) are _extremely_  against tabs!), so I was looking into using `tabbed` along with `tdrop` to add tabs to it.

I can easily run `alacritty` with `tabbed` like this:
```bash
tabbed alacrity --embed
```

So, I thought I would try to use `tdrop` to display that:
```bash
tdrop -am -h 85% -w -2 -x 1 tabbed alacritty --embed
```

But there are multiple issues:
- The `tdrop` window is not appearing as a "drop-down" window, and it's basically a "full" window
- I have a shortcut assigned to opening `tdrop` using `sxhkd`, and what's happening is that every time I press the shortcut, instead of hiding and showing the window, a new window is created

Is there any way to make what I have in mind work?

Oh, and BTW, in case it matters, I'm using Manjaro Linux and i3 🙂

**Comment by noctuid** [comment]
Is there a reason you want to use tabbed instead of something like tmux? I can look into supporting tabbed, but I'd rather not if tmux or screen or something similar would work instead.

**Comment by farzadmf** [comment]
Thank you @noctuid , I _am_ using `tmux`, but there are cases (I must admit that they're rare) where I want to be outside of `tmux`. An example use case for me would be using `tmux` inside a Docker container, where I don't want to be in `tmux` in my own terminal to avoid conflicting shortcuts.

I must admit that this is a very special use case, but for example, with `kitty` (or `guake`), I could easily create a new tab and do what I want, but with `alacritty` with no built-in support for tabs, I was looking for an alternative to achieve the same thing as those terminals.

**Comment by bucknerns** [comment]
+1

**Comment by noctuid** [comment]
Please test with the latest version.

**Comment by farzadmf** [comment]
Seems to be working fine now with `tabbed`, however, in my case of using `alacritty`, the transparency is gone, but I think that's related to `tabbed` rather than `tdrop`
