### ISSUE TITLE
Monitor Aware on i3 Broken

### ISSUE THREAD

**Issue by ibrokemypie** [noctuid/tdrop#82]
On i3 the -m flag makes the dropdown terminal show on the same screen, regardless of which is focuses or which it is run from. This also occurs when running with the -t flag as well. It occurs on the latest commit as of writing, and with both terminals I have tested.

Minimal example:
``tdrop -a -m kitty``

**Comment by farzadmf** [comment]
I think I also have the same issue; I have two different shortcuts to display `alacritty` on different monitors: my `sxhkbd.conf` is like this:
```
{ ctrl + grave }
  tdrop -am -h 85% -w -2 -x 1921 alacritty

{ super + grave }
  tdrop -am -h 85% -w -2 -x 1 alacritty
```

Today, I upgraded to `linux59` and I also upgraded my `nvidia` drivers to `455`, and the shortcuts display my terminal on my "second" monitor (the one located at `x = 1921`), and I'm also using `i3`

I'm not sure if it's the result of display drivers being updated, but seems like the same issue @ibrokemypie mentioned
